### ISSUE TITLE
How to build arrayfire with CUDA support on systems not running a CUDA driver?

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/arrayfire#1043]
The use case here is that I want to build arrayfire with CUDA support on a server system that doesn't have the CUDA driver installed.

From the log:

```
-- Found CUDA: /opt/cuda (found version "7.5") 
-- Boost version: 1.58.0
-- Using LIBNVVM_HOME: /opt/cuda/nvvm
-- /build/arrayfire/src/arrayfire-full-3.1.2/CMakeModules/cuda_compute_capability.cpp
-- CUDA Compute Detection Output: Couldn't get device count: CUDA driver version is insufficient for CUDA runtime version

-- CUDA Compute Detection Return: 1
-- CUDA Compute Detection Failed
-- No computes detected. Fall back to 20, 30, 50
-- Number of Computes Detected = 3
-- Setting Compute 20 to ON
-- Setting Compute 30 to ON
-- Setting Compute 50 to ON
-- CUDA cusolver library available in CUDA Version 7.5
```

But also:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "afcuda" in directory /build/arrayfire/src/arrayfire-full-3.1.2/src/backend/cuda
```

Other packages such as blender that also heavily rely on CUDA work just fine in this setup. I need arrayfire to support this behavior since I'm currently trying to create an official Arch Linux package for it.

The interesting thing to not here is that it definitely find CUDA in /opt/cuda but then still fails.

**Comment by shehzan10** [comment]
So the compute detection can fail and that's why you are seeing the fall back computes of "20, 30, 50". If you want to just build one of them, use -DCOMPUTES_DETECTED_LIST="20;30;..." (or whichever you prefer). You can also use -DCUDA_COMPUTE_20(or other compute)=ON to select each compute independently. To turn off autodetection, use -DCUDA_COMPUTE_DETECT=OFF.

For libcuda, it comes from the driver and not the SDK. The only option is to copy it from a machine that you can find the driver on.

**Comment by pavanky** [comment]
Considering that [the package](https://www.archlinux.org/packages/community/x86_64/arrayfire/?utm_source=dlvr.it&utm_medium=twitter) has been updated, I am closing the issue.
