### ISSUE TITLE
diag() has odd behavior when applied to 1D arrays

### ISSUE THREAD

**Issue by AEHousman** [arrayfire/arrayfire#1209]
As expected,
```
    array baz(3);
    array foo = diag(baz, <anything>, true);
```
throws an exception for invalid size. Remarkably, though,
```
    array foo = diag(baz, <anything>, false);
```
works! If `<anything>` is zero, foo's dimensions are 3,3,1,1. If `<anything>` is -6, foo's dimensions are 9,9,1,1. So it really is anything.

I was expecting diag to work only with 2D arrays,  and if we were really pedantic, 1D arrays with 0 or negative values of the index `<anything>`. (I'm fine with it working with 2D arrays only.)

**Comment by pavanky** [comment]
@AEHousman I think the confusion is because of the way `diag` implements the `true` and `false` options.

- When option is set to `true`, input needs to be a diagonal matrix and output is a particular diagonal.
- When option is set to `false`, input needs to be a diagonal and the output is a diagonal matrix using the input along the specified diagonal.

I hope that clears things up

**Comment by AEHousman** [comment]
Ahh, thanks. I misread the documentation (as usual!) It's possible the C interface is actually clearer; using an arg to switch the mode of a function completely (which is why I misunderstood it!) might be suboptimal.

**Comment by pavanky** [comment]
Yeah we might add two functions to be more explicit in the future.
