### ISSUE TITLE
Add proper documentation for deviceInfo 

### ISSUE THREAD

**Issue by ArnaudBlanchard** [arrayfire/arrayfire#1245]
af::deviceInfo(char *d_name, char *d_platform, char *d_toolkit, char *d_compute);

This is a dangerous function as we do not know the size of the different char* needed. I check (see below) the devprop implementation and it is :  64, 10, 64,10.

It may differ for a different platform ! ...

It should be a define or it should be indicated in the documentation / header of the function

void devprop(char* d_name, char* d_platform, char *d_toolkit, char* d_compute)
{
    static CPUInfo cinfo;
    snprintf(d_name, 64, "%s", cinfo.vendor().c_str());
    snprintf(d_platform, 10, "CPU");
    // report the compiler for toolkit
    snprintf(d_toolkit, 64, "%s", AF_COMPILER_STR);
    snprintf(d_compute, 10, "%s", "0.0");
}

**Comment by pavanky** [comment]
@shehzan10 Add minimum sizes for each buffer.

**Comment by shehzan10** [comment]
This method was done the way it is because we did not want errors because of different versions of C to allocate and free memory. This reason was valid prior to adding `freeHost` function (v3.3).

Me recommendation is that we deprecate this API and add a new function that allocated the required memory internally. Users can then call freeHost on the pointers.

The new api would be
```
void deviceInfo(char **d_name, char **d_platform, char **d_toolkit, char **d_compute);
af_err af_device_info_alloc(char **d_name, char **d_platform, char **d_toolkit, char **d_compute); // Requires new name as no overloading
```
