### ISSUE TITLE
Clean up the interface with Freeimage

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1356]
Right now we are loading in raw data and ignoring any changes that might occur because of the system architecture.  We have fixes in places for certain cases, but that is not the proper way to deal with the data.

Free image documentation specifies how to do this. Check out page 28 of the pdf from here:
[FreeImage3154.pdf](https://github.com/arrayfire/arrayfire/files/186314/FreeImage3154.pdf)

**Comment by 9prady9** [comment]
@pavanky @shehzan10 As part of this, can we use the c++ API of freeimage if it helps us reduce the amount of freeimage code inside ArrayFire ?

**Comment by shehzan10** [comment]
The part about adding C++ API would require linking with FreeImagePlus. This is generally a different package on most linux distros. I don't have a problem with it, but it is another dependency. So that needs to be taken into consideration.

**Comment by 9prady9** [comment]
@umar456 I don't think this issue is valid anymore. If yes, we should close this.

**Comment by 9prady9** [comment]
I don't think this issue is valid anymore. I have checked the freeimage documentation and our code base. We are already handling the color model layout appropriately for 24 bit and 32 bit DIB(bpp - bits per pixel formats) at given below locations.
- https://github.com/arrayfire/arrayfire/blob/master/src/api/c/imageio.cpp#L63
- https://github.com/arrayfire/arrayfire/blob/master/src/api/c/imageio.cpp#L181
- https://github.com/arrayfire/arrayfire/blob/master/src/api/c/imageio2.cpp#L58

If there is something I am missing, feel free to reopen.
