### ISSUE TITLE
Eigen with MKL + Arrayfire = Wrong Eigen results for matrix multiplication

### ISSUE THREAD

**Issue by VitorGuizilini** [arrayfire/arrayfire#1471]
I recently bumped into the following potential bug while trying to use Arrayfire and Eigen+MKL in the same C++ code:

1) I define two NxN matrices in Eigen
2) I calculate the product between the two Eigen matrices
3) I transfer these matrices to the GPU using Arrayfire
4) I calculate the product between the two Arrayfire matrices

If I don't define USE_MKL_BLAS (code gets roughly 2x slower) everything is fine

If I define USE_MKL_BLAS:
   If N  < 34 everything is fine
   If N >= 34 the Eigen results are wrong and the Arrayfire results are correct 

If I remove Arrayfire completely from the code the Eigen+MKL results are always correct.

This is as far as I was able to track this issue, does that make sense? What is Arrayfire doing to Eigen in order to promote these errors when MKL is being used?

**Comment by pavanky** [comment]
@vguizilini can I get some code to see how you are doing this ?

**Comment by vguizilini** [comment]
Here is a minimal example:

------------------------------------------------------------------------------------------------------------------
#include <stdio.h>

#define EIGEN_USE_MKL_ALL

#include <arrayfire.h>
#include <Eigen/Core>

int main()
{
    int n = 40;

    Eigen::MatrixXf eig1( n , n );
    eig1.setRandom();

    Eigen::MatrixXf eig2( n , n );
    eig2.setRandom();

    Eigen::MatrixXf eigm = eig1 * eig2;

    af::array arr1( n , n , eig1.data() );
    af::array arr2( n , n , eig2.data() );

    af::array arrm = af::matmul( arr1 , arr2 );

    std::cout << eigm.array().sum() << std::endl;
    std::cout << af::sum<float>( arrm ) << std::endl;

	return 0;
}
---------------------------------------------------------------------------------------------------------

If I comment EIGEN_MKL_USE_ALL then the sum of both multiplication results is the same. If I leave EIGEN_MKL_USE_ALL, then the results are the same only for n < 34, otherwise they differ by seemingly random values (and the Eigen multiplication is wrong).

**Comment by pavanky** [comment]
@vguizilini can you also printout the output of af::info() ?

**Comment by vguizilini** [comment]
ArrayFire v3.1.0 (CUDA, 64-bit Linux, build 1a52ee1)
Platform: CUDA Toolkit 7.5, Driver: 361.42
[0] GeForce GTX 970M, 6144 MB, CUDA Compute 5.2

**Comment by pavanky** [comment]
@vguizilini That's not even a released version of arrayfire. It's a commit from a development branch from several months ago. Is there any reason you are still on that version of arrayfire ? Can you try the latest version of arrayfire ?

**Comment by pavanky** [comment]
P.S. I tested the code you submitted with the released version of v3.1.0 and the latest release v3.3.2. Both produce proper results.

**Comment by vguizilini** [comment]
I just downloaded and compiled the source files from here:

https://github.com/arrayfire/arrayfire/tree/master

Now, af:info() gives me this:

ArrayFire v3.4.0 (CUDA, 64-bit Linux, build 3ceb2f9)
Platform: CUDA Toolkit 7.5, Driver: 361.42
[0] GeForce GTX 970M, 6144 MB, CUDA Compute 5.2

And the results are still wrong. Can you show me which version you downloaded, so I can try it?

**Comment by pavanky** [comment]
Which version of eigen and MKL are you using ?
What are the outputs you are seeing?

**Comment by vguizilini** [comment]
Eigen: 3.2.8 and 3.3-beta (tried both)
Following advice from somewhere else, I tried disabling MKL support and adding AVX and FMA support, which indeed solved the problem. But it is still much faster if I maintain MKL, so I would prefer to keep that. 

MKL: 11.2
I tracked the issue to the BLAS library in MLK, since 34 is the threshold for Eigen to start using its optimization routines.

I changed the minimal code so that both eigen matrices (n=40) are filled with "1", to facilitate reproducing the results. These are the scenarios:
- If I remove MKL, both eigen and arrayfire give me a sum of 64000 (which is correct). 
- If I put MKL back, arrayfire still gives me 64000, but eigen now gives me different wrong values each time (~200000). 
- If I maintain MLK and remove arrayfire (don't include <arrayfire.h> and remove the corresponding part of the code), eigen gives me the correct value of 64000.

So, the issue only happens when MKL and Arrayfire are both used in the same code, and only the CPU computation (eigen) is affected, not the GPU one (arrayfire). Somehow, the presence of Arrayfire messes up the MKL routines that Eigen is using.

**Comment by pavanky** [comment]
I really do not sure if this is an arrayfire problem. The only thing I can think of asking you to try is to include `arrayfire.h` *after* `Eigen/Core`. It could potentially be that arrayfire and eigen are both defining a same flag that is causing a problem.

**Comment by pavanky** [comment]
@vguizilini can you also show how you are compiling the code?

**Comment by vguizilini** [comment]
I tried every possible combination of header orderings, but nothing seems to work.  I am using the following CMakeLists.txt:

```
cmake_minimum_required( VERSION 2.8 )
project( device )

find_package(MKL)
find_package(Eigen3)
find_package(ArrayFire)

include_directories(
        ${EIGEN3_INCLUDE_DIR}
        ${MKL_INCLUDE_DIRS}
        ${ArrayFire_INCLUDE_DIRS}
)

link_directories(
        ${MKL_LIBRARIES}
)

link_libraries(
        afcuda
        ${MKL_LIBRARIES}
)

add_executable( compare
        src/proj_compare.cpp
)

```

**Comment by 9prady9** [comment]
I have noticed such value issues while using Eigen(with MKL) and ArrayFire using above mentioned compilation approach i.e. without the right set of flags required for MKL.

When I tried ArrayFire (whether built with MKL or otherwise) with correct set of compile options that are generated by https://software.intel.com/sites/products/mkl/mkl_link_line_advisor.htm , I am getting consistent results across: Bare MKL, Eigen with MKL, and ArrayFire.

[Linked gist](https://gist.github.com/9prady9/9b17da1218574d0a69d3d3eeb0a5488d) has the source code and bash script used to generate the binaries.

Based on this, I think the right set of compile options weren't passed to Eigen with MKL code as I would assume Eigen only replaces the API calls automatically, however all the appropriate link options need to be taken care of by Eigen user since Eigen is header only.
