### ISSUE TITLE
ArrayFire installer erased my PATH

### ISSUE THREAD

**Issue by amellnik** [arrayfire/arrayfire#1483]
The installer replaced my entire path with `%AF_PATH%\lib` rather than appending it...  This was on Windows 7 x64 with a very long path.

**Comment by pavanky** [comment]
Hmm this seems to be a bug with the software we are using to create the installer + limitation with windows path length.

@shehzan10 is there any way we can find the number of characters inside `%PATH%` from the installer and do the following in case it becomes too long ?
- Copy contents of `%PATH%` to `%OLD_PATH%`
- Append `%AF_PATH%` to `%OLD_PATH%` and store it under `%PATH%` ?

**Comment by amellnik** [comment]
To anyone else who is having a bad Friday afternoon due to this: see the second answer [here](http://superuser.com/questions/265532/how-to-extract-environment-variables-from-system-restore-point-windows-7-64-bit/265575#265575).

**Comment by pavanky** [comment]
@amellnik terribly sorry about this. We should have been more careful about this.

**Comment by amellnik** [comment]
@pavanky -- no harm done -- it gave me a bit of a fright but it turned out to be fairly easy to recover from.  Cheers -A

**Comment by shehzan10** [comment]
Umm, I'm not really sure why this happened. The installer never touches the"System" PATH.

Unless you are using a really old version of ArrayFire (<= v2.0), the following are the facts:
* While redoing our installer for v2.1, we discovered that Windows/NSIS has a 1024 character limit on the environment variables. This caused issues in our own testing so we made sure never to touch the system PATH.
* We do not query, read, or write to the System PATH.
* What we do is actually use the "User" PATH variable. That's why the installer gives a pop up saying something like "%AF_PATH%/lib was added for user....".
* When writing to the user PATH, the installer checks if AF_PATH already exists, otherwise appends. What you have seen has happened when trying to append when the existing string is more than 1024 characters.
* The 1024 character limit could hit the User Path variable as well, but most people to not use this at all. So it's a way more safer bet than the system PATH.

@pavanky the problem with what you suggested is that the NSIS installer also has a 1024 character limit. So that solution would have the same problem.

@amellnik so I am not really sure why the installer would touch your system path. Unless you are actually talking about the user path.

**Comment by amellnik** [comment]
@shehzan10 This was my user path, and I necessarily have more than 1024 characters in it.

**Comment by shehzan10** [comment]
Yeah that would be the issue then.

One trick I've found is to split the variables so that path itself remains small, and ArrayFire itself is an example of this. 
I have don't something like
```
MYVAR=myvariablecontentsareverylongreallytoolong
PATH=%MYVAR%
```
This is especially useful for something like CUDA. They add a full path to the variable whereas simply using %CUDA_PATH% shortens it quite a lot. 
We could have added the entire path for ArrayFire but having run into the issue, we find the modular way better. 

Any application/command prompt reading the variable will see no difference between the modular way and the full value being there 

I know this is only a work around rather than a solution.  It also keeps you from losing valuable information like what happened today. But the only two other alternates we have are to 
1. Ask the user to check the length and confirm the length is less than 1024. Which in our opinion defeats the purpose of a ready to use installer. 
2. Not add it to PATH at all and just leave it to the user to add it. This defeats the goal of ArrayFire running out of the box.

**Comment by pavanky** [comment]
@shehzan10 I meant we should do something like this if the length of PATH is too big:

If `PATH` was `PATH1;PATH2;...PATHN;`, Change the setup to be the following

`OLDPATH=PATH1;PATH2;...PATHN;`
`PATH=%OLDPATH%;%AF_PATH%`

**Comment by shehzan10** [comment]
We have updated the installer to use a special build of NSIS which allows strings upto 8192 characters (up from 1024).
I think this mitigates the possibility of something like this occurring again.

The updated installer was used to build the ArrayFire v3.4.0 installers which can now be downloaded from arrayfire.com. You can confirm downloading the latest installers using the checksums below.

Checksums for ArrayFire-v3.4.0.exe:
```
SHA1   : ca1e4d20ae80422e5ea17f1766591850358e81f7
SHA256 : 3f2705a9d326aa57bd48a16bda9728c87d7eaf0f5ade01d0658be04118498691
MD5    : 0e46180a199afbff5598d6e94f06bbfa
```
