### ISSUE TITLE
Support eigen?

### ISSUE THREAD

**Issue by bluehope** [arrayfire/arrayfire#1530]
How could I obtain eigenvalues and eigenvectors using arrayfire?

It seems like there was some support before (https://www.accelereyes.com/arrayfire/c/group__factor__mat.htm#gaf97c09bd475b8e0b415de3e73e8a5589), but I can't find them for now.

**Comment by pavanky** [comment]
That was before we went open source. We were using a commercially licensed library at that point. This is not an option right now.

**Comment by bluehope** [comment]
@pavanky I see, by the way cuBLAS and MKL supports eigenvector & eigenvalue functions.
http://www.culatools.com/cula_dense_programmers_guide/
Is there any plan to wrap those functions?

Eigenvector, eigenvalue problems are one of mostly used functions for scientific computings.
I hove arrayfire to support eigen related routines.

**Comment by pavanky** [comment]
There's an open issue over here: https://github.com/arrayfire/arrayfire/issues/904

cuBLAS only implements BLAS routines. cuSolver has the LAPACK routines and right now they do not support eigen value decomposition (only supports SVD under the "eigen" functions). MKL does support it, but that adds support for CPU backend.

MAGMA / clMAGMA does support eigen value decomposition which we can borrow, but it does a significant amount of work on the CPU.

CULA (the library you linked to) is the library we were using before we went open source. We can not use this library because of licensing issues.

Please followup on #904. I am closing this issue as a duplicate.
