### ISSUE TITLE
randu generates values from 0 to 1 inclusive

### ISSUE THREAD

**Issue by kaatish** [arrayfire/arrayfire#1610]
Floating point uniform random number generation does not exclude the value of 1.

**Comment by kaatish** [comment]
Offending lines :

- [OpenCL](https://github.com/arrayfire/arrayfire/blob/devel/src/backend/opencl/kernel/random_engine_write.cl#L14)
- [Cuda] (https://github.com/arrayfire/arrayfire/blob/devel/src/backend/cuda/kernel/random_engine.hpp#L32)
- [CPU] (https://github.com/arrayfire/arrayfire/blob/devel/src/backend/cpu/kernel/random_engine.hpp#L79)

The transformation from `unsigned` to `float` does not take the machine epsilon into consideration.

**Comment by pavanky** [comment]
C++ standard has lower inclusive while the higher value is exclusive: http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution

This will still be a problem when you are doing boxMueller transform because you end up doing log(0). Look at what the wiki explains about this: https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform

**Comment by kaatish** [comment]
Box Muller can be used with `1-u1` and `1-u2` if u belongs to [0, 1).

**Comment by pavanky** [comment]
@kaatish Does multiplying by 1.0 / UINTMAX work (as shown in the wiki example) ?

**Comment by pavanky** [comment]
Apparently this is a common bug:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63176
https://llvm.org/bugs/show_bug.cgi?id=18767

Besides I don't think switching boxMueller to use `1-u1` and `1-u2` when one of them is `0` is a solution.

**Comment by kaatish** [comment]
@pavanky No, this doesn't work.
> Does multiplying by 1.0 / UINTMAX work (as shown in the wiki example) ?

> Besides I don't think switching boxMueller to use 1-u1 and 1-u2 when one of them is 0 is a proper solution.

Why not? Box Muller transform accepts uniformly distributed random numbers. If u1 and u2 are uniformly distributed, so are 1-u1 and 1-u2.
Moreover, The value of infinity is a valid outcome of generating normal numbers. For actual calculations we would want to avoid this data point so it makes sense to avoid 0 in the transform.

**Comment by pavanky** [comment]
@kaatish Yes, they are still uniform. But there is a reason why the suggested way to implement boxmueller is to repeat until they don't fall in that range rather than subtracting the uniform numbers for 1. I assume this is because you are generating `0` (because `log(1-u1)` is `0`) with a higher probability than usual.

**Comment by kaatish** [comment]
@pavanky I see. Alright, we can have a while loop to select values from a valid range. I think it can be done easily for CBRNG types but Mersenne will be problematic.

**Comment by pavanky** [comment]
Can you check this out http://www2.econ.osaka-u.ac.jp/~tanizaki/class/2013/econome3/13.pdf
