### ISSUE TITLE
Adding support for CLBlast

### ISSUE THREAD

**Issue by CNugteren** [arrayfire/arrayfire#1611]
For the past year I have been working on [CLBlast](https://github.com/CNugteren/CLBlast). I believe it will soon be mature enough to replace the clBLAS back-end which you are currently using for the OpenCL version of ArrayFire. I also saw issue #1374 which discusses some problems that CLBlast could solve (better performance on non-AMD GPUs for example). However, CLBlast still relies on the community to run and report tuning results on a variety of OpenCL devices.

Are you open to having CLBlast as an (optional) replacement for clBLAS? If so, is there anything I can do to make integration as easy as possible?

**Comment by shehzan10** [comment]
We are definitely open to providing alternates based on user choices.

Some of the requirements check out immediately, like:
* License - APACHE 2.0 is compatible.
* Cross platform
* C/C++ API is great
* float, double, cfloat, cdouble are all there

Going through your README, I have the following questions for you:
* We like to keep ArrayFire's minimum requirement to Visual Studio 2013. I see that CLBlast requirement is VS 2015. Is this a hard requirement based on some C++11 features that are not available in VS 2013?
* Do you allow static linking across all platforms? This would be important if we are to ship CLBlast with ArrayFire binaries that are hosted on our website.
* You wrote about the performance tuning. Is this something that is compile time or can it also be done when we ship ArrayFire to our users (because we have no control over which devices they use).

If you are interested in starting off a PR, the first step we would like to do is to get a `build_CLBlast.cmake` file to build CLBlast as an external project as an alternate to clBLAS. We can add an option in `src/backend/opencl/CMakeLists` to switch between the two libraries.

Once this is good, we can work on source code switching between clBLAS and CLBlast.

**Comment by CNugteren** [comment]
Thanks for your quick response! Here are answers to your questions:

1. VS 2015 is indeed a requirement because of C++11. A while back I made an attempt to start 'fixing' the code to make it compile under VS 2013. But there is just too much that isn't available - it would require re-writing parts of the code. If this is really needed I can check again what can be done, but it'll cost time. If possible I would like to do it in a separate header/source-file - not polluting the main code to much with VS 2013 specific hacks.

2. I don't think I have tested static linking - it isn't part of the current CMake build. But I don't see why it wouldn't possible. Anything that you know that might be blocking this?

3. Performance tuning is done differently in CLBlast compared to clBLAS. In CLBlast all the tuning data is compiled into the library code itself, whereas clBLAS reads optional tuning data stored on the user's disk somewhere. Through Github I receive new tuning results from CLBlast users which I incorporate into the library. If a user wants to tune for their own device they will have to re-compile the library - or send the results to me and I'll add them to the next release. However, tuning is not required for all devices: if a device is unknown, it will use average best tuning results for similar device type/vendor combinations. For example, a previously unseen AMD GPU (e.g. Fiji) will use a tuning configuration that was on average best across Tahiti, Hawaii and Pitcairn.

Let me know what you think.

**Comment by shehzan10** [comment]
1. VS 2015 would limit how we use CLBlast with ArrayFire. This includes building and testing on our CI server on a regular basis (this would also include building and testing CLBlast on its own on an array of architectures and devices). Essentially, it would become limited to users who are building from source on Windows.
If you can make a workaround using a different set of files, that's fine by me. I'm assuming you would have to do predefined macros or selectively include source files.
2. If you can get static linking and VS2013 and we see that the performance is better than clBLAS, we could consider shipping this with ArrayFire binaries.
3. Got it. This was just for knowledge. At the end of the day, it only matter whether of not CLBlast is faster than clBLAS or not.

**Comment by shehzan10** [comment]
Also, if you want to have a more informal chat about this, hop on to our [gitter](https://gitter.im/arrayfire/arrayfire).

**Comment by pavanky** [comment]
@CNugteren links to any benchmarks ?

**Comment by shehzan10** [comment]
@CNugteren I just started to build CLBlast to see how it looks. And realized I had another question.
It looks like you are using **cl.h** header. What are your thoughts on moving to **cl2.hpp**? We recently made the move with ArrayFire and have only good things to say about it.
Maybe we can open a PR from our end for that.

**Comment by pavanky** [comment]
`cl.h` or `cl.hpp` ?

**Comment by CNugteren** [comment]
@shehzan10 I am using the normal `opencl.h` header, since it is available everywhere. I wrap it using `clpp11.h` (https://github.com/CNugteren/CLCudaAPI) to make it a bit more modern and make resource management (alloc/free) automatic. Surely the official headers have their benefits as well, but I don't think changing at this point will help me the project in any way.

@pavanky Some benchmark results can be found in the [CLBlast git repository](https://github.com/CNugteren/CLBlast/tree/master/doc/performance). Some are a bit old, so they should be updated soon.

**Comment by CNugteren** [comment]
It is now possible to compile CLBlast (the `development` branch for now) under Visual Studio 2013, so that issue is solved. Also thanks to @shehzan10 it is now possible to compile a static library.

**Comment by shehzan10** [comment]
@CNugteren It looks like the tester.hpp file has code that is not supported on VS 2013. Is this something that was missed or purposely left out?
The samples work fine with VS 2013.

**Comment by CNugteren** [comment]
I have added support for VS 2013 for the library, the samples, the tuners, and the clients. Not yet for the tests since they required a dependency (another BLAS). I'll add support for the tests as well as soon as possible.

**Comment by shehzan10** [comment]
@CNugteren is there a way to run the **clients** from a `make` command like there is `test`/`alltest`/`ctest` for the tests?

**Comment by CNugteren** [comment]
I took a look at `tester.hpp` and `testblas.hpp` to be able to compile the tests under Windows. Actually there is a lot that is not supported, this is not trivial and thus will take a bit more time to make work (and still be nice).

About your other question: what would be the use/form of such a make command? There is an R-script in `scripts/graphs` which runs the client multiple times for specific configurations and creates graphs. Perhaps that is what you are looking for?

**Comment by shehzan10** [comment]
> I took a look at tester.hpp and testblas.hpp to be able to compile the tests under VS 2013. Actually there is a lot that is not supported in VS 2013, this is not trivial and thus will take a bit more time to make work (and still be nice).

Yeah I tried to do it as well. There are many variables. That said, most of the issues are with `static consts` and list initializers which can be fixed by moving the initialization out of the class. This would not affect integrating CLBlast into ArrayFire itself, but it could affect testing that we would do on all types of hardware. I would not make this a top priority.

> About your other question: what would be the use/form of such a make command? There is an R-script in scripts/graphs which runs the client multiple times for specific configurations and creates graphs. Perhaps that is what you are looking for?

I wanted to run the performance tests as a single command using CI tools. I can use a bash script to run all of them, but it would have been nice to have a single command. That's ok though.

Lastly, I saw the tests having a `-full_test` option. However, it is not possible to pass this argument using `ctest`. The use of ctest is crucial as it allows generating test reports. I have 3 ways to do this:
* CMake Option variable, say `RUN_FULL_TESTS`, which if set to true, will add the `-full_test` argument to the `add_test` command in CMakeLists.
* Alternately, there can be a CMake String variable like `TEST_ARGUMENTS`, where the user can set any argument that needs to be passed to all tests. For example, this could include `clblas=1`, etc. This option is most flexible.
* Have an environment variable for `-full_test` similar to `CLBLAS_PLATFORM`.

**Comment by CNugteren** [comment]
I fixed the CLBlast testers such that they can be compiled with Visual Studio 2013 as well.

About your run-all-clients request: I still don't really see the purpose. All clients actually have different arguments, so if you are for example setting 'n' to some value it will affect the 'n' for GEMM (which is one dimension of a matrix) and the 'n' for AXPY (which is the length of the vector). I don't think many people may want to run the clients the way you do? What do you think? I would suggest a bash script for such a case since it is more flexible.

**Comment by shehzan10** [comment]
> I fixed the CLBlast testers such that they can be compiled with Visual Studio 2013 as well.

Fantastic! I'll check it out.

> About your run-all-clients request: I still don't really see the purpose. All clients actually have different arguments, so if you are for example setting 'n' to some value it will affect the 'n' for GEMM (which is one dimension of a matrix) and the 'n' for AXPY (which is the length of the vector). I don't think many people may want to run the clients the way you do? What do you think? I would suggest a bash script for such a case since it is more flexible.

I don't think this is of much concern. I was asking mainly for running this on a automated system so was wondering if there is any such feature. Bash scripting works fine for me.

I think I'm more interested in the `full_test` bit of the tests that I requested in my last message. This of course concerns the tests rather than the clients.

**Comment by CNugteren** [comment]
> I think I'm more interested in the full_test bit of the tests that I requested in my last message. This of course concerns the tests rather than the clients.

This is now possible through the `CLBLAST_TEST_ARGUMENTS` environmental variable. You might have to clean CMake and re-run it after you set the variable.

**Comment by CNugteren** [comment]
Since most of the automated tests (http://ci.arrayfire.org/view/Other/) now pass successfully, I started looking at the integration of CLBlast into ArrayFire. I [forked arrayfire](https://github.com/CNugteren/arrayfire) and created a `clblast` branch.

So far I've added some CMake code and made `blas.cpp` support either clBLAS or CLBlast. However, I saw that clBLAS is also used in other parts of the code, including `solver.cpp` and the Magma subfolder. Wouldn't it be nice to abstract everything, e.g. rename clblas_gemm to opencl_gemm and clblasTranspose to opencl_transpose or something? And then have the specific clBLAS and CLBlast code only in `blas.cpp`? This makes it easier to maintain, e.g. in case of API changes in clBLAS or CLBlast, and makes it possible to support other libraries in the future (if any).

**Comment by shehzan10** [comment]
Yes, that should be fine. We do something like that for the blas/lapack set up.

**Comment by CNugteren** [comment]
The suggestion above is [implemented in my fork](https://github.com/CNugteren/arrayfire/tree/clblast): ArrayFire (OpenCL part) is now non-BLAS-specific and there are now two back-ends available: clBLAS and CLBlast. All the CMake logic is also ready, there is now a `USE_CLBLAS` and a `USE_CLBLAST` option. I can make a pull-request so that you can review the code?

One thing still missing from the CLBlast side is a working TRSM/TRSV implementation. That's work-in-progress currently, but would require no more changes from the ArrayFire side since CLBlast provides stubs (they return a 'not implemented' error code currently).

**Comment by CNugteren** [comment]
@shehzan10 
What do you think, shall I make the pull request? If we wait to long the merge might become more complicated? We can still of course have clBLAS as a default and CLBlast as an optional library.

**Comment by shehzan10** [comment]
Feel free to open a PR. That should get a productive conversation going.

**Comment by pavanky** [comment]
This is merged into devel.
