### ISSUE TITLE
Dockerfile for ArrayFire development

### ISSUE THREAD

**Issue by vakopian** [arrayfire/arrayfire#1626]
I've seen mentioned in another thread that you use Docker for building ArrayFire.
It would be really helpful if you could publish the Dockerfile(s) you use internally since it would make setting up a development environment for ArrayFire much easier.
Ideally it would be committed into this repository so it can change together with the project as the dependencies for the whole project change.

**Comment by shehzan10** [comment]
Unfortunately, we do NOT use a docker file for development in house. What we do is simply compile the source in a docker so that we can use older versions of GCC that will ensure the widest compatibility. We do not use it for active development and testing.
There is #1439, which is sort of asking for the same. Are you referring to that?
It would make it easier for coordination to just have one issue open for docker.
Would you mind commenting there? We could look into what will need to go into the docker file based on the requirements there.

**Comment by vakopian** [comment]
@shehzan10 I just added a Dockerfile in #1439. Please see if it's useful enough to be added to the repository.
