### ISSUE TITLE
`timeit` isn't working properly.

### ISSUE THREAD

**Issue by serialhex** [arrayfire/arrayfire#1667]
I just noticed that `timeit` isn't working properly, output:

```
time .\bin\phase-unwrap.exe
ArrayFire v3.4.1 (CUDA, 64-bit Windows, build b9055b1)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] Quadro K2000, 2048 MB, CUDA Compute 3.0
Time for bench_roi: 0.04s
Time for bench_correct: 1.14s
Time elapsed: 16s


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 21
Milliseconds      : 405
Ticks             : 214055075
TotalDays         : 0.000247748929398148
TotalHours        : 0.00594597430555556
TotalMinutes      : 0.356758458333333
TotalSeconds      : 21.4055075
TotalMilliseconds : 21405.5075
```

snippit of interest:

``` C
printf("Time for bench_roi: %2.2fs\n", timeit(bench_roi));

std::chrono::steady_clock::time_point begin =
    std::chrono::steady_clock::now();

printf("Time for bench_correct: %2.2fs\n", timeit(bench_correct));

std::chrono::steady_clock::time_point end =
    std::chrono::steady_clock::now();

std::cout
    << "Time elapsed: "
    << std::chrono::duration_cast<std::chrono::seconds>(end - begin).count()
    << "s"
    << std::endl;
```

It's reporting that the `bench correct` function only takes ~1 sec, while it really takes ~15.  it looks like the `bench_roi` is being reported properly (and other things seem to be reported properly also).  I'm not sure if I could send code that reproduces this error fully, as it's within a proprietary application, but I'm making a number of arrays, tiling them, doing joins, and other fun things, and they are ~[5000, 5000, 3] in size.

This isn't dire for me, I'm just trying to get a feel for where I need to optimize, but I thought you'd like to know.  Thanks and take care!

**Comment by shehzan10** [comment]
`timeit` runs multiple iterations of the same function to get an average time. It is not expected to match real time because of the multiple iterations.
The `std::chrono` code you have more or less should match if you use [`af::timer`](http://arrayfire.org/docs/timing.htm).

If you are interested, here is the code for timeit: https://github.com/arrayfire/arrayfire/blob/devel/src/api/cpp/timing.cpp#L84

**Comment by pavanky** [comment]
@serialhex `timeit` runs several iterations, synchronizes once and returns the average time taken. This was written because this is the best way to benchmark an asynchronous function. Users not using timeit can use `af::timer()` to get begin and end times but they usually end up committing one of the following mistakes:

1) They do not call `af::sync()` in which case they are getting the time to queue the function rather than actual run time.

2) They call `af::sync()` after every call, in which case they are measuring synchronization time which can be costly.

**Comment by serialhex** [comment]
Ahhhhh!!! Okay, so it's just a misunderstanding on my part!!  Taking this into consideration I got the following:

```
time .\bin\phase-unwrap.exe
ArrayFire v3.4.1 (CUDA, 64-bit Windows, build b9055b1)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] Quadro K2000, 2048 MB, CUDA Compute 3.0
Time for bench_roi: 0.04s
Time for bench_correct: 1.13s
Time elapsed: 1083ms


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 21
Milliseconds      : 916
Ticks             : 219166882
TotalDays         : 0.000253665372685185
TotalHours        : 0.00608796894444444
TotalMinutes      : 0.365278136666667
TotalSeconds      : 21.9166882
TotalMilliseconds : 21916.6882
```

with the following code:

``` C++
printf("Time for bench_roi: %2.2fs\n", timeit(bench_roi));

printf("Time for bench_correct: %2.2fs\n", timeit(bench_correct));

std::chrono::steady_clock::time_point begin =
    std::chrono::steady_clock::now();
bench_correct(); // factored it out to check time just once
std::chrono::steady_clock::time_point end =
    std::chrono::steady_clock::now();
std::cout
    << "Time elapsed: "
    << std::chrono::duration_cast<std::chrono::milliseconds>(end - begin).count()
    << "ms"
    << std::endl;
```

which is *much* closer to each other (1.13s & 1.08s).  I didn't realize `timeit` was running multiple iterations.  Thanks for the clarification!!
