### ISSUE TITLE
af::rotate need theta to be array.

### ISSUE THREAD

**Issue by artheru** [arrayfire/arrayfire#1737]
A usage in my current project:

```
gfor (seq i, n)
  rot(span,span,i)=rotate(img, thetas(i));
```

In current arrayfire, rotate doesn't accept a array "theta" parameter, but a float "theta". Thus cannot be "gfor"ed.

**Comment by pavanky** [comment]
@artheru You can currently use transform to implement what you are looking for.

**Comment by artheru** [comment]
transform works

**Comment by pavanky** [comment]
@shehzan10 @9prady9 Do you guys think we should have a new rotate function to do this as well ?

**Comment by shehzan10** [comment]
> @shehzan10 @9prady9 Do you guys think we should have a new rotate function to do this as well ?

This was on the plate once when I was rewriting the `rotate` function. However, it quickly became apparent that since we use the `crop`/`expand` argument, batching this for multiple rotations under the expand option means that each image dimensions can be completely different, which is obviously not going to work.

So due to the restrictions of how batching would work for multiple rotations, this is not feasible.

Even in the transform case, it is NOT ideal to store the results as channel of the same image unless the crop option is set.

**Comment by pavanky** [comment]
@shehzan10 how about we just limit the new function to what transform does i.e. not have crop / expand ?

**Comment by pavanky** [comment]
@shehzan10 in other words, just a wrapper around transform.

**Comment by shehzan10** [comment]
It will end up being a wrapper around transform anyway. I don't think it is particularly effective. All this function would do is take an array of floats and convert them into an array of transform. This can quite easily be done by the user.

I see that it might make a convenience function, but I'm not sure how widely it will get used given its limitation of being cropped.

**Comment by pavanky** [comment]
@shehzan10 we can implement this in C++ instead of C.

@artheru would you be interested in contributing this ?

**Comment by artheru** [comment]
Sure, I'll make a pull request with function: rotateGfor(im, angle).

**Comment by pavanky** [comment]
@artheru Since it is C++, The function `rotate` can be overloaded.
