### ISSUE TITLE
 RuntimeError : Could not load any ArrayFire libraries (Python)

### ISSUE THREAD

**Issue by QuantScientist** [arrayfire/arrayfire#1873]
Hi,
I installed everything on Ubuntu and I can run C++ examples. 
However, when using python I get this error:

![2017-07-19 11_39_50-u7 running - oracle vm virtualbox](https://user-images.githubusercontent.com/18743986/28358391-5e1b6fe0-6c77-11e7-9e62-27ff4d56e52b.png)

What am I doing wrong?

**Comment by 9prady9** [comment]
From the screenshot, it looks like you are using only CPU backend. Can you make sure all the libraries required by CPU backend are also in `LD_LIBRARY_PATH` ?

Going forward, if the issue is related to python bindings, please open the issue over [here](https://github.com/arrayfire/arrayfire-python/issues).

**Comment by QuantScientist** [comment]
Hi , thanks, 
I am indeed using only a CPU backend for now. Which other libraries are you referring to?

**Comment by 9prady9** [comment]
[CPU backend dependencies](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#cpu-backend-dependencies)

**Comment by QuantScientist** [comment]
Nowhere does thE documentation state having to add CPU dependencies to LD_LIBRARY_PATH.

**Comment by 9prady9** [comment]
If they are installed to standard locations on Ubuntu, they don't need to be added anywhere and the library loading should be smooth without any issues. However, the error you got - "ArrayFire couldn't load libraries" suggests otherwise - some dependency is either missing or not installed in standard location. Hence, I suggested you to make sure you have the dependencies available through LD_LIBRARY_PATH.

**Comment by QuantScientist** [comment]
Sure, I understand, but everything is standard, no amendments whatsoever, and as mentioned C++ works without any issues, and no one reported this error before (except for one person on OSX).

**Comment by 9prady9** [comment]
I just noticed that the library SO version number is `3.6.0`. Did you build the library from source(devel branch on git) ?

When you say C++ examples, did you try running the examples with `_unified` suffix ?

**Comment by QuantScientist** [comment]
Yes, I built them from source, run the CPU version in C++.

**Comment by 9prady9** [comment]
I am confused by your last comment, did you mean you were able to run `helloworld_unified` C++ example fine ?

**Comment by 9prady9** [comment]
The reason I ask if `helloworld_unified` worked fine is - If the `helloworld_unified` works fine, there is not reason for python bindings to not work because python bindings loads libaf.so(unified af library) that in turn loads the actual backend libraries.

If you want to review the instructions that are listed on arrayfire-python wiki page, here's the link https://github.com/arrayfire/arrayfire-python/wiki

**Comment by pavanky** [comment]
Please move this discussion to arrayfire-python.
