### ISSUE TITLE
Performance of slicing 3D arrays depends on the size of the third dimension

### ISSUE THREAD

**Issue by stasikz** [arrayfire/arrayfire#1908]
Hallo,

Maybe it is a bug, or I missunderstood something, but it seems, that by increasing a third dimension of the 3D array and trying to access the slice, it slows down the program depending on the size of the 3rd dim.

Here is my example:

```
array buffer = af::constant(100, Y, X, Z); 
// later in code the following code is executed periodically 
array my_slice =buffer.slice(i); 
// do some manipulation with my_slice e.g.      
my_slice = image + my_slice * 5; 
buffer.slice(i) = my_slice; 
```

If I increase the Z-dimenstion e.g. from 64 to 128 the speed dropes by 50%.
I thought that by slicing I get a contiguous copy of the data slice from the buffer and after manipulations 
I copy a contiguous data block again into a buffer at the same position. But it seems that arrayfire do some data rearrangements which reduce the execution speed.

**Comment by pavanky** [comment]
When you are writing to `buffer.slice()` it needs to make an additional copy. This is because arrayfire arrays are copy-on-write. 

This is done to ensure the following cases work:
```
array a = af::randu(5,5);
array b = a; // both a and b point to same memory
b.col(1) = 1; // Makes a copy for b and updates te slice. Does not modify a
```
But if there are no other references to that memory, the additional copy should not happen. You can control this by trying out the following:

1) Try using `buffer(span, span, i)`. I am not sure if `buffer.slice` creates an unnecessary reference.
2) Try using 
```
array my_slice = buffer(span, span, i); 
my_slice = my_slice.copy(); // This will ensure There are no other references to buffer.
```
3) If these don't help, try to see what other references `buffer` might have in the code and try to avoid them.

If you have further questions, come over to slack for a chat: arrayfire-org.slack.com
Here's the invite link: https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ
