### ISSUE TITLE
Add support for sparse sparse arrays addition

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#1911]
Hi all
Looks like 
sparse + sparse = sparse
is not supported at least with 3.5.0:
`  std::vector<float> onefloat; onefloat.push_back(1);
    af::array values(1, &onefloat[0]);

    std::vector<int32_t> oneint; oneint.push_back(1);
    af::array rowIdx(1, &oneint[0]);
    af::array colIdx(1, &oneint[0]);

    af::array A1 = af::sparse(3,3, values, rowIdx, colIdx, AF_STORAGE_COO );
    af::array A2 = af::sparse(3,3, values, rowIdx, colIdx, AF_STORAGE_COO );

    af::array A3 = A1 + A2;
    af_print(A3);
`
Caught exception when trying CUDA backend
ArrayFire Exception (Function not supported:301):
In function af::array af::operator+(const af::array&, const af::array&)
In file src/api/cpp/array.cpp:914

I m today converting the sparse arrays to some temp dense arrays using af::dense(sparseArray) but I suppose that s inefficient. 
Could anyone confirm first it is just not implemented, ie not a bug ?
Kind
W.

**Comment by pavanky** [comment]
@WilliamTambellini 

> Could anyone confirm first it is just not implemented, ie not a bug ?
The message in the exception is correct. This operation is not implemented. Sparse arrays do not support all the functions. The most requested ones were added first.

Coming back to the question, I am curios, is this for machine learning ? If so are you trying to add 2 sparse arrays or is your goal to add multiple sparse arrays before adding to a dense array ? I ask because this is something that could potentially benefit arrayfire-ml as well.

**Comment by WilliamTambellini** [comment]
Thanks P.
- yes this is for machine learning, at least NeuralNet
- my need is both to do simple sparse+sparse and also adding some sparse to a dense array
- that could also benefit arrayfire-ml: sparse ops are probably a must have for NLP machine learning
W.

**Comment by 9prady9** [comment]
This has been addressed #2312
