### ISSUE TITLE
support for cuda unified memory

### ISSUE THREAD

**Issue by jtc25** [arrayfire/arrayfire#2090]
Since memory copy to/from the host is usually the slowest part of the whole signal processing problem. Adding the unified memory should be priority # 1.

**Comment by 9prady9** [comment]
After reading through [basic details of CUDA unified memory](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#um-unified-memory-programming-hd) and its feature starting with Kepler cards till now, it is not a single stop solution to the problem you mentioned above. Hardware support for page migration got introduced in PASCAL only, so earlier generation cards might not see as much performance gains as one might expect out of using unified memory.

With unified memory, the user/developer would have to take care of GPU page faults to get maximum performance of any given kernel - please look [here](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#um-performance-tuning) for the general guidelines to get good performance while using unified memory.

It would help in the case of multi-GPU scenarios. However, even in those cases `memory thrashing` & `page faults` should be avoided/prevented at all costs.

I am just listing my thoughts on how I think support for unified memory should be implemented as follows:
* Add a environment variable such as [AF_MEM_DEBUG](http://arrayfire.org/docs/configuring_environment.htm#af_mem_debug), lets say `AF_CUDA_UNIFIED_MEM` so that ArrayFire's memory management functions use managed memory calls instead of unmanaged memory calls.
* Add additional methods to af:array class, perhaps, such as `af::array::cuPrefetchAsync(int destinationDevice)`  and `af::array::cuMemAdvise(int destinationDevice, enum)` etc. to prefetch the data before kenel execution
* May be add some mechanism to check and prevent thrashing and pages faults if such support is provided by CUDA runtime.

@umar456 @pavanky Any thoughts or ideas ?

**Comment by jtc25** [comment]
I have developed an  application using managed memory with the CUDA toolkit 9.1 & C++. I use a makefile to build it. In this app I have performed comparisons of memallocmanaged and mallocmemory transfer to/from the host.  As I mentioned previously the data transfer in my app is the major bottleneck. When I execute a 1024x1024 complex convolution  in approx 1 ms, the unmanaged memory data transfer version takes approx. 7  ms(14 ms if I count both input and output) , the managed memory version data transfer is not required. As you can see the gpu is not a problem, but transferring data to/from the gpu is a the limit to gpu performance. I have used the Arrayfire builtin image capability to display the results(this eliminates the need to output the results), but I still must transfer the input data to the gpu.
      I prefer to use Arryfire with Xcode 9.3.  Arrayfire is much easier and more efficient  in development time. However, at present since Arrayfire does not support this type of memory management, I must use other  methods. In my opinion, the option to add managedmemory(Unified memory) option should be the number one priority in Arrayfire improvement.
Keep me up to date, if this feature is added. I would offer my time to support this effort, but I don't know how much help I could be.
