### ISSUE TITLE
CMake crashes with vcpkg toolchain file

### ISSUE THREAD

**Issue by mlloreda** [arrayfire/arrayfire#2140]
We've been experimenting with [vcpkg](https://github.com/Microsoft/vcpkg) in order to improve the build experience on Windows. To find installed dependencies, the `CMAKE_TOOLCHAIN_FILE` variable needs to point to vcpkg's toolchain file, `$VCPKG/scripts/buildsystems/vcpkg.cmake`.

However, setting `-DCMAKE_TOOLCHAIN_FILE` when building with ArrayFire examples causes CMake to crash due to a stack overflow.

While #2139 prevents the stack overflow, the VS solution file necessary to build ArrayFire is not being generated. The solution, for now, is to set the toolchain file but disable the ArrayFire examples via `-DAF_BUILD_EXAMPLES=OFF`.

**Comment by umar456** [comment]
This happens because ArrayFire and vcpkg override the default `add_library`, `add_executable`, and `find_package` macros/functions. ArrayFire is doing this in the examples because we want the examples CMakeFile.txt file to closely resemble the usage to the end user ,but we want the targets of those executable to be prefixed with the `example_` prefix to avoid any conflicts with other internal targets(blas and fft in particular). 

This is causing an infinite loop because we forward the add_* commands to the default one which then call the functions overloaded by vcpkg and so on. One possible way to fix this is by creating a CACHED INTERNAL variable which is set on the first call to add_library or find_package and skipping the call to _find_package on the second call.
