### ISSUE TITLE
af::seq takes double but returns f32

### ISSUE THREAD

**Issue by net147** [arrayfire/arrayfire#2224]
It should be possible to make af::seq return a f64 array to avoid loss of precision. It seems af::seq always returns a f32 array even though it expects double arguments.

**Comment by umar456** [comment]
af::seq is an object that defines a range. It should only be used for indexing operations. We allow this conversion because it was a legacy feature and it makes some things easier. You should be using [iota](http://arrayfire.org/docs/group__data__func__iota.htm) if you want to control the type of the output array.
