### ISSUE TITLE
`af/random.h` and `af/sparse.h` are missing 

### ISSUE THREAD

**Issue by prasunanand** [arrayfire/arrayfire#2261]
Hi, 

I installed libarrayfire-unified-dev on ubuntu-18.04 via `apt`.
`libarrayfire-unified-dev/bionic,now 3.3.2+dfsg1-4ubuntu1 amd64 [installed] Development files for ArrayFire (unified backend)`

The header files  `af/random.h` and `af/sparse.h` are missing in `/usr/include`.

This is the `arrayfire.h` file in `usr/include/arrayfire.h` => https://gist.github.com/prasunanand/ca928078a6edac478c20af243770df4b

Is this desirable ?

**Comment by 9prady9** [comment]
I can confirm that those headers are not mentioned in arrayfire.h for 3.3.2 release which was fixed in one of the later releases. `3.3.2` is 7 releases far from the current stable release. I think the package needs to be fixed to use latest version, 3.6.1.

If you can use 3.3.2 only, you can easily work around this by manually including the required header.

**Comment by prasunanand** [comment]
Thanks @9prady9 .
