### ISSUE TITLE
The array is shrinking being initialised

### ISSUE THREAD

**Issue by Tony2v** [arrayfire/arrayfire#2278]
Hello! Can somebody enlighten me what's happenning here:
I'm creating an `af::seq(N)` where N=1000;
Then i'm multipling it by number `af::Pi` and initialising an array object with the product like that:
`af::array Prod = af::array(af::Pi * af::seq(N))`
Some magic happening there: if the size of `af::seq(N)` was N=1000, the size of the `af::array` product is becoming a 999!
The thing is that the size of `af::seq Prod = af::seq(af::Pi * af::seq(N))` is still N = 1000!

**Comment by Tony2v** [comment]
Right, basically what i'm doing is calculating the Hamming window function:
`af::array Hamming_win = af::array(0.54 - 0.46*af::cos(2 * Pi*af::seq(N_strobe) / (N_strobe - 1))).as(f64);`
and it should be the length of 1000, while N_strobe = 1000, but it's not.

**Comment by Tony2v** [comment]
ok, my solution was to transfer `seq(N_strobe)` to `af:array(seq(N_strobe)) ` asap and use it in the code above.
`af::array Hamming_win = (0.54 - 0.46*af::cos(2 * Pi*af::array(af::seq(N_strobe)) / (N_strobe - 1))).as(f64);`

**Comment by 9prady9** [comment]
Sorry about the delay, I was on vacation.

I think what you are seeing is because of wrong usage of `af::seq` constructor. 

`Seq` class has operator overloads which will be invoked by the statement `af::Pi * af::seq(N)` resulting in another `af::seq` instead of what you are expecting it to be, a `af::array`. Hence, I asked you earlier what was it you are expecting `af::Pi * af::seq(N)` to be.

For the above mentioned reason, your workaround gives you your expected output. You can also do `af::array strobeArray = af:::seq(N_strobe)` and use `strobeArray` later.

Please close the issue if the question has been answered.
