### ISSUE TITLE
Calling custom functions in Julia: the kernel dies?

### ISSUE THREAD

**Issue by 4lrdyD** [arrayfire/arrayfire#2455]
I used as reference the example provided in :[Interoperability with OpenCL ](http://arrayfire.org/docs/interop_opencl.htm). when I use a code like:

  ```
void copy(const af::array &A, af::array &B,size_t length) {
      // 2.Obtain the device, context, and queue used by ArrayFire 
      // 3.Obtain cl_mem references to af::array objects
      cl_mem * d_A = A.device<cl_mem>();
      cl_mem * d_B = B.device<cl_mem>();

      // 4. Load, build, and use your kernels.

      // Set arguments and launch your kernels
      //kernel is the function build in step 4
      clSetKernelArg(kernel, 0, sizeof(cl_mem), d_A);
      clSetKernelArg(kernel, 1, sizeof(cl_mem), d_B);
      clEnqueueNDRangeKernel(af_queue, kernel, 1, NULL, &length, NULL, 0, NULL, NULL);
      // 5. Return control of af::array memory to ArrayFire
      A.unlock();
      B.unlock();
   }
```
I call this function in Julia as follows:

`ccall((:copy,"path/to/dll"),Cvoid(Ref{af_array},Ref{af_array}),Af.arr,Bf.arr)`

`Af `and `Bf` are ArrayFire arrays, the call works as expected and `Cf` show the correct result,  the problem is when I use directly `B=A` only to test i.e.

```
  void copy(const af::array &A, af::array &B,size_t length) {        
     B=A;//only to test
  }
```
the call works , but when I want to print `Cf` the kernel dies, this made me doubt if I'm using the correct way to write and call this functions.

Some of the Arrayfire functions incorporated in Julia that I saw, call functions that have `af_array` as arguments that are different from the arguments `af::array`. Well I want to change the arguments, then I do this:

```
void copy(const af_array &dA, af_array &dB,size_t length) {

//this to be able to use A.device and B.device
array A=array(dA);
array B=array(dB);

//steps 2 to 5 in the original code 

}
```
It doesn't work in C or in Julia, the question is if I want to use `af_array` as arguments how I get the device pointer? or what is the corret way to handle this functions to avoid problems when I call them in Julia?

thanks in advance.

**Comment by 4lrdyD** [comment]
the `af_get_device_ptr` seems to be a solution to get the device pointer from an `af_array` object, 
[calling custom C ArrayFire functions in Julia #229](https://github.com/JuliaComputing/ArrayFire.jl/issues/229)

**Comment by 9prady9** [comment]
Sorry about the delay, the function you found is the right way to get device pointer from af_array. In fact, there are quite a few functions with `af_` prefix(C API) that lets you fetch or set attributes of the data represented by the opaque handle `af_array`.

Our C++ API (`af::array` and anything under namespace af) is a wrappers\ around the C-API. We strongly recommend using one API instead of mixing C and C++ API as it could potentially lead to unforeseen issues around resource(array data) management.

If you want to use C++ API, your earlier call `array.device<type>()` is right way to get device pointer. That member function of af::array essentially calls `af_get_device_ptr` of [C API](http://arrayfire.org/docs/group__method__mat.htm).

However, if you are exchanging data across language boundaries, I would suggest C-API instead of C++ API. Every C++ API of ArrayFire can be achieved by equivalent C-API call. For some operations like indexing, it might take more than one API call, but that is what C++ API does too. You should go with `void copy(const af_array &dA, af_array &dB,size_t length)` if you cannot any specific function that you are trying to find out, you can also quickly reach out to us on our [slack](https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ) channel.

**Comment by 4lrdyD** [comment]
Thanks for the advice @9prady9, now I understand some details that I overlooked. I'll review the channel, it will be very useful.
