### ISSUE TITLE
blas and anisotropic_diffusion tests fail for cuda backend

### ISSUE THREAD

**Issue by hyperbomb** [arrayfire/arrayfire#2462]
After succesfully installing and testing the cuda toolkit & drivers, I built arrayfire and ran its tests as follows:
```
#on remote: scp cuda-repo-ubuntu1604_9.2.148-1_amd64.deb foobar:
sudo dpkg -i cuda-repo-*_amd64.deb
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo apt-get update
sudo apt-get install cuda=9.2.148-1
echo 'export PATH=/usr/local/cuda-9.2/bin${PATH:+:${PATH}}' | sudo tee /etc/profile.d/cuda.sh
sudo reboot

cat /proc/driver/nvidia/version
nvcc -V
cd /usr/local/cuda-9.2/samples
sudo make
cd bin/x86_64/linux/release/
./deviceQuery
./bandwidthTest 

git clone --recursive https://github.com/arrayfire/arrayfire.git
cd ./arrayfire
sudo apt-get install -y build-essential git cmake libfreeimage-dev
git checkout v3.6.1
git checkout -b v3.6.1
mkdir build
cd build/
cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_EXAMPLES=OFF -DAF_BUILD_OPENCL=OFF -DAF_BUILD_CPU=OFF
make -j4
make test
./test/blas_cuda &>~/blas_cuda.log
./test/anisotropic_diffusion_cuda &>~/anisotropic_diffusion_cuda.log
```
Unfortunately, the following two tests failed:

[blas_cuda.log](https://github.com/arrayfire/arrayfire/files/2990517/blas_cuda.log)
[anisotropic_diffusion_cuda.log](https://github.com/arrayfire/arrayfire/files/2990518/anisotropic_diffusion_cuda.log)

Please advise on how to resolve this issue. Thanks!

**Comment by 9prady9** [comment]
Anisotropic diffusion failed due to `TEST_FILE_NOT_FOUND`. I see that you did a recursive clone and the sub-modules should have been cloned fine but something isn't adding up there. I have checked the `test/data` submodule hash in our repository for 3.6.1 tag and that is correct and relevant files are present. Can you please check files used by `test/anisotropic_diffusion.cpp` are found on your disk.

blas_cuda failure can be ignored as it is due to slightly higher error value but it is still within an acceptable range. We have fixed(increased the error tolerance range) this in 3.6.2.

**Comment by hyperbomb** [comment]
@9prady9 Thanks for the prompt response, submodule update seems to have fixed the issue for me for the anisotropic_diffusion test. Thanks!
