### ISSUE TITLE
Question : Is the C Pointer of CPU backend reachable in C++?

### ISSUE THREAD

**Issue by dotChris90** [arrayfire/arrayfire#2502]
Hello Team, 

I just was asking myself the following question. 

If we use the CPU - the array should be stored into the main memory (right?). So is there a way to get back the underlying pointer as representation of the used array? I do not mean to get a copy of the array as C Pointer because copy leads to higher memory consumption but I really mean the e.g. double pointer of a double array and so it is not twice in memory (as array and as pointer).

Moreover I would like to ask which dll / API must be taken for this - just ask because interested in porting it to some other languages. :D

**Comment by umar456** [comment]
Yes you can. The device pointer will give you the pointer to the underlying array. It will perform a copy in case its nonlinear(a view into a larger array) so that you can access it like an array. There is another function named `af_get_raw_ptr` which will just give you the underlying pointer. You will have to access this pointer using the stride and dims array otherwise you could access data out of bounds.

We only have a single DLL for each of the backend. For the CPU you would target afcpu.dll

**Comment by 9prady9** [comment]
When it comes to porting, we recommend using unified API - `af.dll`. We have https://github.com/arrayfire/arrayfire-rust and https://github.com/arrayfire/arrayfire-python that use unified API too. You can look at them for getting an idea.

**Comment by 9prady9** [comment]
If you are interested in looking at existing projects for other language bindings which are a work in progress, please look under https://github.com/arrayfire . You are welcome to contribute to them and provide feedback instead of starting it from scratch.

**Comment by dotChris90** [comment]
thanks for the answers. :)

just saw there already exist many nice interop packages for other languages.

will check them and I thinky question is answered. :)
