### ISSUE TITLE
Cache compiled kernels to disk

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#2503]
With the latest nvrtc changes incorporated into ArrayFire, the initialization times for the initial launch will go up significantly. This is because we are compiling these kernels at runtime instead of embedding them into the library. We did this to reduce the binary size of the binary which has steadily gone up with every release.

An approach to reduce the overhead would be to write the compiled binaries to disk and load them on the first call. This avoids compiling to code to the intermediate representation and then to binary by the driver. Loading these binaries should be faster than compiling them from source.

We could also do this with JIT kernels and further reduce the initialization overhead.

One of the things to consider is where are we going to store these binaries. On Linux we can store them in the tmp folder or a hidden folder in the user's directory. On Windows we need to find a standard location for these files. Systems may be loading from a network drive which could hurt the performance so this location needs to be configurable.

**Comment by 9prady9** [comment]
#### For Windows
The best way to store the kernels is on per-user-account basis. We can can query `AppData` path of the user running the program using [SHGetKnownFolderPath](https://docs.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) using the flag `FOLDERID_AppDataProgramData`.

#### For Linux
I don't like the idea of `tmp`, there is no guarantee of persistent storage there. `tmp` potentially gets cleaned up on reboot or startup. We should store it under `$HOME/.arrayfire` . This per-user location can also be used to store other configuration data we potentially might want to save to disk in future. One such avenue is environment variables: right now can be set either in command line or in bashrc; we can have a configuration file(whichever may be the format) inside this per-user folder and use those settings on library load.

**Comment by cschreib-ibex** [comment]
This seems like a very desirable feature for improving runtime performances. Is there any plan to include this in ArrayFire in a coming release?

**Comment by 9prady9** [comment]
Unfortunately, this won't make the next release, v3.7. We shall update this issue for future discussions and/or progress related to this feature.

**Comment by cschreib-ibex** [comment]
Ok, thank you for the update!

**Comment by cschreib-ibex** [comment]
This has become an important issue for us. Because of the kernel compilation overhead, our processing pipeline takes about 20 seconds when run "cold" (first time run), and just 2 seconds when "hot" (second run within the same process). 

Our current solution to keep the processing time more constant is to execute an "initialization" phase when the program starts up, which essentially boils down to running the whole pipeline on some dummy data, before our user starts processing their own. This makes processing time almost constant on user data, however the total runtime is actually higher because of that dummy processing. And 20 seconds to load up our software feels very slow...

If we could somehow dump the kernel cache at the end of the "initialization" phase, we could execute the "initialization" in house and ship the kernel cache alongside our application. In production, we would only have to load up that cache into ArrayFire, which would be much quicker for the user. There might still be a few JIT compilations happening after that, but they would be few enough that the impact on runtime could be ignored (and if not, we would just need to update the kernel cache to include them).

This would probably be simpler to implement than caching individual kernels on disk, and it wouldn't require choosing a temporary folder as the programmer using ArrayFire would choose where to save/load the kernel cache. This cache could be an asset that is shipped with our program (if the target GPU is known), or it gets built on the user's machine when the program is installed. 

From our point of view, all that would be needed are the following two functions:
```c++
af::saveKernelCache(path);
af::loadKernelCache(path);
```

Is there interest in having such a feature in ArrayFire? If so, we'd be willing to contribute (or assist in) the implementation.

**Comment by umar456** [comment]
We would be interested in this feature but I am not sure if the safe and load approach will work in all cases. Each device will generate different binaries for the kernel because they target different architectures. If your customers are running on a new device or one that is not compiled in house you could crash your program. You would still be able to assign a directory where you could dump the kernels and you could potentially ship this directory to your customers. We just need to be careful about what device we targeted when the kernels were compiled.

Typically on Linux, the /var/lib/<name> directory is used to store temporary data for a library. The home directory is often mounted on a network drive so there could be issues with it being located on the home directory. @9prady9 mentioned the solution on Windows and we can also set the location via API calls like in your comment.

Internally we have 3 places where we need to address this issue. Regular kernels are handled through the binary. We compile these kernels into the binary and they are loaded by the library during startup. We are moving away from this approach because this increases the binary size significantly. 

The second API is the nvrtc based compilation. This is used by the JIT and some kernels in the CUDA backend. This is handled [here](https://github.com/arrayfire/arrayfire/blob/master/src/backend/cuda/nvrtc/cache.cpp). This is a newer API we are moving to as we move forward.

The third API is in the OpenCL backend. This requires you to compile the OpenCL files then use the clGetProgramInfo to retrieve the binaries from the program. This is going to be more labor intensive because this is spread out throughout the OpenCL backend and will require more work.

Additionally we need our backends to be resilient to changes in the system. Here are a couple of scenarios which we should consider.

1. GPUs changed so kernels must be recompiled
2. The directory was deleted or moved
3. The file system is write only
4. The binaries read from the file system are corrupted.
5. The name of the kernel is the same but the internals of the binaries have changed because it is updated or in active development.

We would be interested in a contribution of any kind. If you want we are available on our Slack channel if you want to discuss details or have questions about the internals of our code.

**Comment by cschreib-ibex** [comment]
Thanks for merging these changes! Any idea when that will be available in a formal release?

**Comment by 9prady9** [comment]
We are hoping to make a fix release soon, like end of month or so. It is not yet set in stone, but that's the goal. Since these are internal changes and doesn't meddle with API/ABI, we will push this in the fix release. Will keep you posted.

I am closing this one since it is in master @cschreib-ibex Thanks once again for the contribution!
