### ISSUE TITLE
Canny Edge Detector calculation errors

### ISSUE THREAD

**Issue by greennbeans** [arrayfire/arrayfire#2588]
Whilst porting some code from python to ArrayFire, I have noticed some differences/errors with the Canny Edge Detector :

1. There is an error in the nonMaxSuppression kernel for the case of dx and dy <0. The linear interoplation coefficient alpha is being assigned a negative value, and hence the calculation is wrong. The error can be easily observed in the test data (eg  fast16x16)  as the top right edge is missed.

2. The X and Y Sobel derivates are applied in a swapped around fashion (compared to python). I beileve the implementation in ArrayFire in the nonMaxSuppression kernel is the issue as the code looks like it is assuming row major ordering, instead of the actual column major ordering.

3. As a note, the code in then nonMaxSuppression  kernel uses the array dims for indexing rather than the strides which appears unsafe, as it could return incorrect results.

4. The Canny implementation is far less flexible than the python one. In python you can configure the smoothing kernel, have more useful and flexible threshold inputs, and can mask regions. Given that there are so many variations possible in the canny, it might be more useful to provide public access to the 2 unique kernel functions in the implementation - nonMaxSuppression  and edgeTrackingByHysteresis, and that way, uses can customise the canny implementation as required.

**Comment by 9prady9** [comment]
@greennbeans Which backend have you tried to use ? Did you notice the problem (1) in all backends ?

Can you point me to the lines for (2) & (3).

Can you please provide the link the API you are referring to.

**Comment by greennbeans** [comment]
At this stage, I have tried only the cpu and cuda back ends. From inspection of the kernels show they are implemented in the same way. As the same test data is used for all backends, I would expect the same issue for open CL.

For CPU: arrayfire/src/backend/cpu/kernel/canny.hpp
(1) is at line 87
(2) is lines 40-47
(3) is throughout this file - in particular lines 33, 35, 36, 40-47

For Cuda : arrayfire/src/backend/cuda/kernel/canny.cuh
(1) is at line  130
(2) would be lines 85-92 - this uses same structure as CPU, but I haven't fully understood what it is doing.
(3) Doesn't seem to apply to CUDA.

The API I am calling is canny() http://arrayfire.org/docs/group__image__func__canny.htm
This is implemented in arrayfire/src/api/c/canny.cpp in the function cannyHelper. Of the steps in this filter, everything can already be done via the public api except nonMaximumSuppression and edgeTrackingByHysteresis. The python function we have used is https://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.canny

**Comment by 9prady9** [comment]
I will look into the section you have pointed out for (1)

I doubt that row / column major ordering has any effect on sobel's derivatives because the equations are identical along both dimensions.

(3) is not a bug, we are correctly skipping a 1-pixel border while moving from one column to the next column. This doesn't apply to CUDA but the same algorithm is implemented even in CUDA/OpenCL - leaving 1-pixel border while processing the inputs.



Regarding the scikit's API:

Masking the input is easily achieved using indexing in ArrayFire.
```
array a = image(seq(startx, endx), seq(starty, endy);
array res = canny(a, ...);
```

We do provide threshold ratio parameters also.

The following are the only customizations not present right now./
- `sigma`paramter
- `use_quantities` toggle

We can add another API that provides the above additional parameters.

**Comment by 9prady9** [comment]
`CannyEdgeDetector/6.ArraySizeEqualBlockSize16x16` is that the test you are referring to, for which the output is wrong ?

**Comment by greennbeans** [comment]
For the tests, all the image comparison tests are impacted. The ArraySizeLessThanBlockSize10x10 and ArraySizeEqualBlockSize16x16 input images (fast10x10.test and fast16x16.test) are both very clear squares/rectangles. The expect output data shows the canny detecting the corners - except the top left corner is completely missed which is definitely wrong. If you fix (1), the top left corner is also detected.

Applying the same fix causes failures in the OtsuThreshold that uses data from the woman.jpg test file

**Comment by greennbeans** [comment]
For (1), I can confirm it is the same on all platforms.
For (2), this only applies to the CPU backend. Both CUDA and OpenCL implement the calculations correctly. The CPU backend generates the wrong results.
For (3), this also only applies to CPU as well. I am not talking about the border, rather if stride[1] is not equal to dims[0], this will generate the wrong result. For example, if this kernel was called from an array where we have called rows() to use only a subset of rows, it will index the data incorrectly. In the canny, we always have a "clean" array, but if this kernel was used more generally it could be a problem.

**Comment by greennbeans** [comment]
With respect to the functionality of the canny function:

- The mask parameter is applied in a far more sophisticated way in scikit's API. It allows regions to be masked, and it is specially handled by the gaussian smoothing.
- The manual threshold parameters work differently in scikit's API. In that API, it is divided against the "dmax" for the type (1.0 for float) and then directly used. For ArrayFire, the surpressed magnitudes are then normalised between 0-1 (note that min is always zero due to the edge), and the threshold is applied. As a result, the thresholds are not interchangeable.

**Comment by 9prady9** [comment]
(3) I think that case is not possible because of the way ArrayFire is written at the moment. Even sub-arrays get evaluated upon `Array::get()` call that fetches the pointer. But I do agree what you said is true if the kernel by itself is pulled out and used else where.

scikit API discussion contd.
- From what I read from the docs you shared earlier, it is simple sub region of given input image. What kind of special behavior are you talking about ? Can you please share an example.
- I will look into thresholds, perhaps we can change the behavior without waiting for new API introduction.

**Comment by 9prady9** [comment]
@greennbeans Just looked the lines you pointed out about case where both dx and dy are negative. I will send in a fix PR soon. Thanks for reporting it.
