### ISSUE TITLE
max overload makes the wrong choice

### ISSUE THREAD

**Issue by r-barnes** [arrayfire/arrayfire#2610]
[The documentation](http://arrayfire.org/docs/group__reduce__func__max.htm#ga4459daf5a3b081fb4ee15eb49d8c902a) speaks of two ambiguous signature for max:
```c++
array af::max(const array &in, const int dim = -1)
T af::max(const array &in)
```
My compiler apparently favours one of these incorrectly:
```
../src/442.cpp:168:33: error: cannot convert ‘af::array’ to ‘double’ in initialization
     double amp_max = af::max(amp);
```
Moreover, it's dangerous to have these two signatures be so similar since the `auto` keyword is recommended for most code and, in this case, can lead to problems.

**Comment by umar456** [comment]
Hey r-barnes,

The two functions you listed can easily be distinguished by the compiler by including the template parameter. The first function allows you to return an array that contains the max across an axis where as the second one will return one value for the max of all arrays. You can use this with the auto keyword like this:

```
auto a = max(data);
auto val = max<float>(data);
```

The compiler needs the template parameter for the second function because the return value is templated. The compiler cannot deduce the return type so it picks the first.

**Comment by r-barnes** [comment]
This worked great, thanks!
