### ISSUE TITLE
gfor usage

### ISSUE THREAD

**Issue by bkimbrough** [arrayfire/arrayfire#2651]
I am trying to use gfor as shown below.

gfor(seq i, 1)
	{
       A.col(i + 1) = flat(range(dim4(xsize, ysize)), i);
	}

 
Both the A.col(i+1) expression and the ,i in the flat function are flagged.  The error on the flat function is:   error C2660: 'af::flat': function does not take 2 arguments.

How can I make this work.  I noticed in your examples that math with the seq i should work.

Thanks.
Brad

**Comment by umar456** [comment]
There are several restrictions to the gfor construct and it has some limited use cases. Often gfor constructs can be implemented more clearly using batching constructs.

In this case it looks like you used the flat function incorrectly. [Flat](http://arrayfire.org/docs/group__manip__func__flat.htm) only takes one argument instead of 2. Here you are passing `i` as the second argument to flat.

I suggest you bring these types of issues(usage, and questions regarding functionallity) on the google groups or our slack channel. You can find the links on the main README.md file or on the GitHub front page. GitHub issues are mostly there for bugs.
