### ISSUE TITLE
CUDA Error: out of memory

### ISSUE THREAD

**Issue by AlbertLiDesign** [arrayfire/arrayfire#2699]
Hello everyone,
I'm a beginner of arrayfire. I just wanna test the speed of solving matrics. But I found if I defined a 20000 by 20000 matrix, complier will return "CUDA Error: out of memory".  What should I do? Could you please help me to solve it?

Best wishes

```
#include <iostream>
#include <cstdio>
#include <arrayfire.h>
#include <time.h>

using namespace std;

int main()
{
    const size_t num =20000;
    try
    {
        clock_t start1 = clock();
        af::array A1 = af::randu(num, num);
        af::array B1 = af::randu(num, num);
        clock_t end1 = clock();
        cout << "Running Time 1: " << (double)(end1 - start1) / CLOCKS_PER_SEC << endl;
        clock_t start2 = clock();
        A1.unlock();
        B1.unlock();  
        af::array X = af::solve(A1, B1);
        af::eval(X);
        clock_t end2 = clock();
        cout << "Running Time 2: " << (double)(end2 - start2) / CLOCKS_PER_SEC << endl;
    }
    catch (const std::exception&e)
    {
        fprintf(stderr, "%s\n", e.what());
    }
    return 0;
}
```

![image](https://user-images.githubusercontent.com/39052060/71507165-7fb9c600-28be-11ea-95c1-8211c455a556.png)

**Comment by AlbertLiDesign** [comment]
The error information is:
Running Time 1: 0.655
ArrayFire Exception (Device out of memory:101):
In function void *__cdecl cuda::MemoryManager::nativeAlloc(const unsigned __int64)
In file src\backend\cuda\memory.cpp:149
CUDA Error (2): out of memory

In function class af::array __cdecl af::solve(const class af::array &,const class af::array &,const af_mat_prop)
In file src\api\cpp\lapack.cpp:89

**Comment by 9prady9** [comment]
Each 20kx20k matrix of float type is about ~ 1.4G, and you created two of them. solve's implementation might create additional workspace location, this size might need some good amount of device memory.

What is the device you are using and how much memory does it have ?

**Comment by AlbertLiDesign** [comment]
> Each 20kx20k matrix of float type is about ~ 1.4G, and you created two of them. solve's implementation might create additional workspace location, this size might need some good amount of device memory.
> 
> What is the device you are using and how much memory does it have ?

Hi, thank you for your help. My gpu is RTX2060 which has 6G memory. I guess it is not enough to occupy all the memory. But how to manage my gpu memory?

**Comment by 9prady9** [comment]
As I said earlier, I believe the upstream implementation, i.e. cuSolver since you are using CUDA backend, is trying to allocate more memory for rough workspace.

Is it possible to divide your problem into smaller problems , for example divide the problem along one of the dimensions into smaller sets ?

**Comment by AlbertLiDesign** [comment]
> As I said earlier, I believe the upstream implementation, i.e. cuSolver since you are using CUDA backend, is trying to allocate more memory for rough workspace.
> 
> Is it possible to divide your problem into smaller problems , for example divide the problem along one of the dimensions into smaller sets ?

Thank you again.
My problem just is a test. In fact, I just wanna to learn how to implement solving big matrices. Could you please give me an example? How to divide a big matrix into smaller problems? I'm sorry to prompt this problem that looks so basic.

**Comment by 9prady9** [comment]
Got you.

Usually, when matrices are that large you should look at the possibility of them being sparse. If they are, then storing the entire matrix is a irrelevant question.

You should look at the similar questions on **[ResearchGate](https://www.researchgate.net/post/What_is_an_efficient_algorithm_to_solve_a_large_106_106_linear_equation_system)** and **[MathExchange](https://math.stackexchange.com/questions/2735/solving-very-large-matrices-in-pieces)** .

Apparently there are multiple ways to address your question - what if the matrix doesn't fit on memory ? - you should probably read through relevant literature. I personally haven't dealt with such large problems regarding solve.

I am closing the issue since it is not related to ArrayFire codebase or logic. However, if you feel to continue this conversation with other community members, please feel free to open a google forum post at https://groups.google.com/forum/#!forum/arrayfire-users
