### ISSUE TITLE
af::print terminates program under CUDA backend

### ISSUE THREAD

**Issue by DarkStar1997** [arrayfire/arrayfire#2703]
```
    af::array arr = af::randn(1, 2);
    af::print("This is it ", arr);
    std::cout << "It's done\n";
```
The code above gives the following output:

```
This is it 
[1 2 1 1]
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function void print(const char*, af_array, int, std::ostream&, bool) [with T = float; af_array = void*; std::ostream = std::basic_ostream<char>]
In file src/api/c/print.cpp:87



In function void af::print(const char*, const af::array&)
In file src/api/cpp/util.cpp:19
Aborted (core dumped)
```

I am on an updated Arch Linux system with Arrayfire 3.6.4 installed from the repos with CUDA  10.2 and GCC 9.2

**Comment by 9prady9** [comment]
@DarkStar1997 I use Arch Linux as my regular dev system and my packages are update to date. When I try `af::print` function instead of `af_print` macro, I don't face any issues using 3.6.4 tag. There is probably however the difference that, I have the tag built in a separate worktree for testing purposes. I assume you are using our website binary. If that is the case, can you please try with `AF_PRINT_ERRORS` environment variable set to `1` and also try running the example through gdb to get throw loc.
