### ISSUE TITLE
simple pad and crop functions

### ISSUE THREAD

**Issue by shersoni610** [arrayfire/arrayfire#2729]
Hello,

I could not find any simple Pad and Crop Image functions? Are they available with some other names?

Thanks;

**Comment by 9prady9** [comment]
@shersoni610 We don't have functions per say, it is indexing (http://arrayfire.org/docs/indexing.htm ) operation that helps you achieve what you are looking for.

However, recently, we added https://github.com/arrayfire/arrayfire/pull/2682 padding function that is more performant than indexing for certain cases.

I am closing the issue since it is not an actual feature request. Questions such as these are better suited for our slack channel. https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ
