### ISSUE TITLE
af::array constructor from initializer list

### ISSUE THREAD

**Issue by pauljurczak** [arrayfire/arrayfire#2825]
As an option for short array, in addition to
```
int h_buffer[] = {23, 34, 18, 99, 34};
array A(4, h_buffer);   
```
can we get 
```
array A(4, {23, 34, 18, 99, 34});
```
which will allocate the memory and initialize it with values from initializer list.

**Comment by 9prady9** [comment]
Yes, that could be helpful for short arrays.
```c++
// 1D array
array::array(std::initializer_list<T> list); 

// Other cases
array::array(const af::dim4 &dims, std::initializer_list<T> list);
```

However, these could very easily implemented around existing constructors, which is the most probable implementation we might do as well.
```c++
af::array fromList(std::initializer_list<T> list) {
  return af::array(list.size(), list.begin());
}

af::array fromList(const af::dim4 &dims, std::initializer_list<T> list) {
  return af::array(dims, list.begin());
}
```

@umar456 what do you think ?

**Comment by 9prady9** [comment]
Now that I have written it out, I am doubtful if the above implementation would work with CUDA/OpenCL backend because the copy to GPU memory is asynchronous in nature and the initializer list allocation may not stay valid for that long. I would have to verify that. Neverthless, it could be easily implemented on top existing constructors I think.

**Comment by pauljurczak** [comment]
Looks good to me. For the moment, I'm using CPU only, so it should work fine.

**Comment by 9prady9** [comment]
I checked CUDA and OpenCL backends, what I suggested should work fine for those also.
