### ISSUE TITLE
Performance problems on AMD cpu

### ISSUE THREAD

**Issue by jzupka** [arrayfire/arrayfire#2837]
It looks like that arrayfire has some big performance problems on EPYC cpu
https://www.phoronix.com/scan.php?page=article&item=intel-5220r-6226r&num=3
compared to this https://www.phoronix.com/scan.php?page=article&item=intel-5220r-6226r&num=4
the performance should be competitive with others cpus.

**Comment by 9prady9** [comment]
Our CPU backend is for a purely sequential backend (no native SIMD magic etc.) except for few cases where usage of upstream libraries for BLAS, FFT, LAPACK functionalities gives an extra boost. That is the case because of upstream's own implementation being multi-threaded or SIMD.

I believe phoronix benchmarks are generated using installers available on our website. Our website installers are built with Intel-MKL. Given these facts, I think it is Intel-MKL that is performing super inefficiently on AMD processors compared to Intel Processors.

@umar456 Is there something I am missing ?

**Comment by jzupka** [comment]
Oh ok thank you for explanation. Then  `export MKL_DEBUG_CPU_TYPE=5`
should be enough for almost fixing the problem. I don't tested this but it works with matlab.

**Comment by 9prady9** [comment]
Yes, I have read about this environment variable, although it is not documented in Intel MKL documentation. So, I am not sure how reliably we can use it.

[MKL_DEBUG_CPU_TYPE](https://www.pugetsystems.com/labs/hpc/How-To-Use-MKL-with-AMD-Ryzen-and-Threadripper-CPU-s-Effectively-for-Python-Numpy-And-Other-Applications-1637/#UsingMKL_DEBUG_CPU_TYPE=5withAMDCPU\'s) That article talks about it being useful even with latest Ryzen Thread Rippers. So, I would think it should work with Epyc processors too.
