### ISSUE TITLE
Windows Binary Installer -- afcuda.dll is absolutely massive... why?

### ISSUE THREAD

**Issue by scottmudge** [arrayfire/arrayfire#2863]
I have compiled my fair share of CUDA-dependent libraries, many of them massive... OpenCV, TensorFlow, custom-rolled libraries, etc. Even the largest and most complex of these libraries is smaller than the pre-compiled afcuda.dll distributed on the ArrayFire website.

afcuda.dll is 963,264 KB (~940 MB) -- why on earth is it so massive? The '.nv_fatb' PE section, constituting all of the nvcc compilation, is 851,898 KB, taking up a vast majority of the file size.

It is 2.68x **larger** than its debug symbols file. For comparison, the afcpu.dll file is ~8x *smaller* than its debug symbols file. 

Would it be possible to change the default build configuration to link against the non-static CUDA runtime and just distribute the much smaller cudart64_10.dll file? Another good strategy to shrink the file size is to exclude unnecessary CUDA architectures. Are every possible `gencode=` and `arch=` permutation being used?

I've also noticed that with MSVC, some linker and compiler flags dramatically bloat library sizes, especially with respect to CUDA libraries. A couple of these in particular are /GL and /LTCG, which when used with libraries like PCL can cause the compiled library to be 8x larger, when CUDA support is enabled.

It is simply untenable to distribute software binaries linked against afcuda.lib on Windows, when the associated DLL is a gigabyte in size.

**Comment by scottmudge** [comment]
Never-mind, I see this is a duplicate.

Well I hope it can be shrunk down in the future. In the meanwhile I'll just compile it myself w/ the appropriate build configuration.

**Comment by 9prady9** [comment]
That is alright, here is summary of the reason.

We are aware of the large binary size problem, in fact it is not just windows even Linux binary is considerably large because of the following mentioned reasons . 
- We can't anticipate/assume what GPU the user will target or run their arrayfire based program/application on. Therefore, to ensure the user can run it on any target GPU, we build for each CUDA compute version since 3.0 till 7.5 i.e. about 12 compute versions.
- We can just compile using 3.0+PTX compute target, but that would result in sub-optimal performance for higher compute versions.

Having said that, we are constantly improving the CUDA backend to reduce the binary size. #2437 #2560 #2790 were done as part of the work towards this goal. We were also able to reduce the Linux binary via #2535 by splitting the debug symbols into a separate file.

We have more work in the pipeline towards reducing the binary size.
