### ISSUE TITLE
Unneccessary usage of enum parameter `af_border_type` in `af_maxfilt` and `af_minfilt`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [arrayfire/arrayfire#2885]
For both `af_maxfilt` and `af_minfilt` the enum `af_border_type` is used for the `edge_pad` parameter.

The documentation ([max](http://arrayfire.org/docs/group__image__func__maxfilt.htm), [min](http://arrayfire.org/docs/group__image__func__minfilt.htm)) notes only 2 values of the enum can be used, `AF_PAD_ZERO` and `AF_PAD_SYM` (which if true I would suggest should mean a different parameter type should be used).

In the code, both of the functions `af_maxfilt` and `af_minfilt` feature the line `ARG_ASSERT(4, (edge_pad == AF_PAD_ZERO));`, from my understanding (and some testing) this appears to mean you can really only pass the value `AF_PAD_ZERO`. 

This seemingly makes the parameter pointless.

Am I missing something?

**Comment by 9prady9** [comment]
The idea behind having the enum parameter is to enable potential future expansion of types of border padding. This is also the reason we have a default parameter value in our C++ API. So far, we haven't had any requests for other types of border padding, hence the delay in expanding the padding support for this function. You are welcome to contribute or raise a feature request if it is needed for your use cases.

I see that you are using Rust wrapper which doesn't have default arguments, thus left with an additional parameter. It could be marked as optional but even then you would end up passing `None` and let the library default to `AF_PAD_ZERO`. Therefore, I chose the explicit way, pass `ZERO` instead of `None`.

**Comment by 9prady9** [comment]
@JonathanWoollett-Light Closing the since the original query has been answered. Feel free to raise a feature request for other types of padding if they are required for your use cases.
