### ISSUE TITLE
Computer turn off when blas_opencl running

### ISSUE THREAD

**Issue by vsufiy** [arrayfire/arrayfire#2906]
Hello, everybody!
I run blas_opencl project at GPU and it's work fine.
After changed cycle limit from 2048 to 2\*2048 in code
`         for (int n = 128; n <= 2*2048; n += 128)`
my computer worked unpredictably.
Usually computer turned off, but sometime worked fine or rarely turned off only display.
I tried change limits 2048+k\*128 by k from 1 to 16 and detected that 2048+3\*128 worked fine.
When k>3 computer turned off.
My computer configuration:
CPU Core i7-2600, RAM 16 Gb, GPU Radeon VII (16 Gb).
Software:  
Windows 7 Professional 64 bit, 
Visual Studio 2017, 
ArrayFire 3.7.1, 
and installed last driver version for GPU win7-radeon-software-adrenalin-2020-edition-20.4.2-apr23.exe 
Could somebody help me to solve this problem?
Thank you

**Comment by 9prady9** [comment]
If the compute code is utilizing the same GPU connected to the display, then windows reset's the driver/GPU to recover from any issue that corrupts the driver state. This is known by the short form [TDR](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/timeout-detection-and-recovery). Try printing out the size of memory you are using from the benchmark and check if that is huge. Since it is running fine with initial range, I believe you exhausting the memory resource I think.

Our slack channel is a better place for questions such as these. Here's the invite https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ and we respond quite promptly over there.

**Comment by vsufiy** [comment]
Thank you, I will try to fulfill your recommendations
I watched memory volume in Radeon Software.  GPU memory was only loaded at 15% only

**Comment by 9prady9** [comment]
Had a discussion with the user over slack channel. I wasn't able to reproduce this on AMD APU (A10 7850K's Spectre R7). So far, the issue seems specific to either the driver or GPU. I have requested the user to test it on linux, hopefully that will help it identify if it is driver issue or not.

Will post further updates progressively

**Comment by 9prady9** [comment]
Based on the tests carried with the help of the user, the issue seems to be happening on only Windows but not on linux with the same GPU. Immediate difference in the environment is driver version. 
- Windows Driver version:                                3004.8 (PAL,HSAIL)
- Ubuuntu Driver Version                                  3075.10 (PAL,HSAIL)

Investigation is still WIP

**Comment by 9prady9** [comment]
This seems like a driver issue on Windows for this particular GPU as we were not reproduce identical issue on different OS or using different AMD card, APU or discrete card.
