### ISSUE TITLE
Memory leak in OpenCL backend

### ISSUE THREAD

**Issue by laser101** [arrayfire/arrayfire#2917]
I think I've discovered a memory leak in the OpenCL backend which occurs during a call to the `array::device()` method.

Specifically, in `arrayfire/src/backend/opencl/api.cpp` at line 7

```cpp
namespace af {
template<>
AFAPI cl_mem *array::device() const {
    cl_mem *mem_ptr = new cl_mem;
    af_err err      = af_get_device_ptr((void **)mem_ptr, get());
    if (err != AF_SUCCESS)
        throw af::exception("Failed to get cl_mem from array object");
    return mem_ptr;
}
}  // namespace af
```

The allocation of a `new cl_mem` instance on the heap is not released, and the documentation does not indicate to the user that they need to call `delete` on the resulting pointer to release the resource. Subsequent calls to `array::unlock()` obviously don't release the resource either.

Apologies if I've misunderstood this (perhaps it is a reference counted resource?), but I would appreciate some clarification.

Many thanks.

**Comment by umar456** [comment]
You are right. the cl_mem object is not going to be deleted although the underlying buffer will still be managed by the ArrayFire memory manager. This should be documented in the OpenCL interop page. because we cannot change this behavior until the next major release. We can add a v2 version of the device function in the next minor release that will address this leak. Thanks for reporting the issue.
