### ISSUE TITLE
var of a constant array is not always zero

### ISSUE THREAD

**Issue by liuyadong** [arrayfire/arrayfire#2934]
Hi, I got a 2.55795e-13 from

```
#include <arrayfire.h>

using namespace af;

int main(void)
{
  array x = constant(5.5, 3, 3);
  float varx = var<float>(x);
  af_print(x);
  printf("varx = %g\n", varx);
  return 1;
}
```
Output:
```
x
[3 3 1 1]
    5.5000     5.5000     5.5000 
    5.5000     5.5000     5.5000 
    5.5000     5.5000     5.5000 

varx = 2.55795e-13
```

Any way to guarantee a zero?

**Comment by liuyadong** [comment]
and this
```
  array x = constant(5.5, 3, 3);
  float xmu = mean<float>(x);
  float xmin = min<float>(x);
  float xmax = max<float>(x);

  printf("xmu-xmin = %g\n", xmu-xmin);
  printf("xmu-xmax = %g\n", xmu-xmax);
  printf("xmax-xmin = %g\n", xmax-xmin);
```
```
mux-minx = -4.76837e-07
mux-maxx = -4.76837e-07
maxx-minx = 0
```

**Comment by 9prady9** [comment]
@liuyadong As far as my knowledge goes, I think e-13 is of enough higher power to be considered zero. Especially after doing some operations on a bunch of zeros i.e. calculate variance of a set of zeros.

If you need much higher precision, you can use doubles.
```
        array x = constant(5.5, 3, 3, f64);
        double varx = var<double>(x);
        af_print(x);
        printf("varx = %g\n", varx);
```
```
x
[3 3 1 1]
    5.5000     5.5000     5.5000 
    5.5000     5.5000     5.5000 
    5.5000     5.5000     5.5000 

varx = 8.87469e-31
```

**Comment by pavanky** [comment]
@9prady9 is this on CPU or GPU ? Also it might make sense to pass in a "tolerance" factor and return 0 if the output is less than tolaerance.

**Comment by 9prady9** [comment]
I assumed it was on GPU for the user @liuyadong , can you please confirm on what device you tried the code.

@pavanky It's a GPU. There is more than one way to achieve such tolerance control.
- Application level code.
- Provide an extra argument for every function that needs one- at least a good amount of them have use such control.
- Provide some sort of domain (image-processing, vision etc.) specific tolerance control.

I personally don't like per function approach because such argument is not related to the function/algorithm in question. I don't exactly like per-domain tolerance either, but it helps with grouping the tolerance control and avoids changing the API of the entire library, if not many functions. Perhaps there are more ways, I couldn't think of anything else as of now.

**Comment by liuyadong** [comment]
@pavanky @9prady9 It's a GPU, but doubles on CPU make no essential difference. I understand there's no "correct" way to perform this, but Armadillo seems doing well on this situation:
```
#include <armadillo>

using namespace arma;

int main()
{
  vec x(9); x.fill(5.5);
  double xmin = x.min();
  double xmax = x.max();
  double xmu = mean(x);
  double xvar = var(x);
  
  printf("xmu-xmin = %g\n", xmu-xmin);
  printf("xmu-xmax = %g\n", xmu-xmax);
  printf("xmax-xmin = %g\n", xmax-xmin);
  printf("xvar = %g\n", xvar);

  return 0;
}
```
```
xmu-xmin = 0
xmu-xmax = 0
xmax-xmin = 0
xvar = 0
```
Not a comparison about which one is better. I'm trying to transfer from Armadillo, apparently more code and carefulness are needed for now.

**Comment by pavanky** [comment]
@liuyadong arrayfire uses running mean instead of doing sum / count at the end. This was done to avoid overflow when the arrays get large. Downside of this is that they use more numerical operations which may result in loss of precision.
