### ISSUE TITLE
Potential dangling pointer with af_get_default_random_engine()

### ISSUE THREAD

**Issue by cschreib-ibex** [arrayfire/arrayfire#2940]
``af_get_default_random_engine()`` returns a handle to a ``thread_local`` ``RandomEngine`` object. From what I understand of the implementation, calling ``af_release_random_engine()`` would delete the ``RandomEngine``, and any future call to ``af_get_default_random_engine()`` would then return the same handle, which is now dangling (references a deleted object). 

In fact, whenever ``af_get_default_random_engine()`` is used internally in ArrayFire, I see that ``af_release_random_engine()`` is never called. Likewise, the C++ API actually makes a copy of the returned handle, so the original default engine doesn't get deleted.

If this is intended, it may be worth mentioning this special case in the documentation of either ``af_get_default_random_engine()`` or ``af_get_default_random_engine()`` (or both).

**Comment by umar456** [comment]
Correct. You shouldn't be deleting the internal random engine because its not managed by the user. This reference is for the functions that do not accept the random engine as part of their function call. You can pass a random engine that you manage yourself which could be deleted when you are done. You could also call the retain function on the random engine you get from af_get_default_random_engine, after which you should be able to delete it.

Please feel free to update the documentation and submit a pull request. I think this would be useful information to have in there.
