### ISSUE TITLE
[Build] make error building for CPU on Ubuntu 20.4

### ISSUE THREAD

**Issue by JacquesBass** [arrayfire/arrayfire#3003]
Description
===========
I successfully installed the prerequisites:

```
libfftw3-dev is already the newest version (3.3.8-2ubuntu1).
liblapacke-dev is already the newest version (3.9.0-1build1).
libopenblas-dev is already the newest version (0.3.8+ds-1ubuntu0.20.04.1).

libfontconfig1-dev is already the newest version (2.13.1-2ubuntu3).
libglfw3-dev is already the newest version (3.3.2-1).

libfreeimage-dev is already the newest version (3.18.0+ds2-1ubuntu3).
```

and I  did the cmake, it says "No package 'cblas' found", but libopenblas-dev is installed and later it says: "CBLAS library found"

```
cmake .. -DCMAKE_BUILD_TYPE=Release

-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found suitable version "2.0", minimum required is "1.2") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Includes found
-- CBLAS Symbols FOUND
-- CBLAS library found
-- MKL: Thread Layer(Intel OpenMP) Interface(4-byte Integer)
-- Autodetected CUDA architecture(s):  6.1
-- CUDA_architecture_build_targets: Auto ( 6.1  )
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jadmin/kaalam.github/arrayfire/build
```
then, `make -j32` fails with:

```
make -j32  

[  0%] Built target cpu_sort_by_key_char
[  0%] Built target bin2cpp
[  0%] Built target cpu_sort_by_key_int

/snip/

[ 25%] Building CXX object src/backend/cpu/CMakeFiles/afcpu.dir/__/common/module_loading_unix.cpp.o
[ 25%] Building C object src/backend/cpu/CMakeFiles/afcpu.dir/__/__/__/extern/glad/src/glad.c.o
[ 25%] Built target opencl_sort_by_key_uint
[ 26%] Linking CXX shared library libafcpu.so
[ 26%] Built target afcpu                                  
make: *** [Makefile:163: all] Error 2
```

The Makefile, at line 163 has `$(MAKE) -f CMakeFiles/Makefile2 all` which looks like a call to the whole shabang, so not very informative.

Build Environment
-----------------

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

Compiler version: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

Build environment: cmake version 3.16.3, GNU Make 4.2.1

Git origin  https://github.com/arrayfire/arrayfire.git
Git branch master

**Comment by JacquesBass** [comment]
While logging out the error I found out it is due to compiling nvidia "cuda_runtime.h" with gcc 9.x. The file includes a "host_config.h" which contains.

``` 
#if __GNUC__ > 8

#error -- unsupported GNU version! gcc versions later than 8 are not supported!

#endif /* __GNUC__ > 8 */

```

The error was not visible due to the fancy coloring on the console, but when redirected to a file I caught it.

I solved it making gcc 8.x the reversible default as described in: https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa

**Comment by JacquesBass** [comment]
Maybe it would be a good idea to warn users about the incompatibility. I didn't really need cuda, I didn't select it on purpose, but it auto-detected.

**Comment by 9prady9** [comment]
Auto-enabling detected backends is the expected behaviour while building ArrayFire. Please note that we do provide a cmake option `AF_BUILD_CUDA` that can be set to `OFF` as needed. Given below is  the example command to do it.

```bash
cmake .. -DAF_BUILD_CUDA:BOOL=OFF
```
We already describe the default behaviour and availability of the above cmake option in our github wiki. Here is the link to that
document. https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#building-arrayfire

As far as the compiler compatibility with nvcc - nvidia's CUDA toolkit provided compiler, it could possibly be checked in our CUDA backend CMake file if we maintain a table sort of information about each CUDA toolkit's maximum supported compiler version on each operating system. I am not so sure if we should so something like that given that nvcc does throw an error right away if incompatible host compiler is used and message is not difficult to understand. @umar456 What is your take on it ?

**Comment by JacquesBass** [comment]
Thank you.
