### ISSUE TITLE
Please add c++ binding for af_imax()

### ISSUE THREAD

**Issue by avidov** [arrayfire/arrayfire#3069]
I'm using af_imax() to implement NN pooling layer for Flashlight. Unlike typical ArrayFire API, af_imax() has only C API (no C++ one). Could we please add one? I can send a PR.

**Comment by syurkevi** [comment]
The C++ equivalent should just be max(array &val, array &idx, const array &in, const int dim) 
Pardon any confusion due to different names, this was done since the C-api can't support overloading based on function params.
Implementation here:
https://github.com/arrayfire/arrayfire/blob/096221d6e0040f092a259094d623e03856389ad5/src/api/cpp/reduce.cpp#L174

**Comment by avidov** [comment]
Thank you!
