### ISSUE TITLE
Will this work on FreeBSD? [Question]

### ISSUE THREAD

**Issue by inf3rno** [arrayfire/arrayfire#3074]
I have a FreeBSD 12.2 with [OpenCL](https://www.freshports.org/devel/opencl) currently. FreeBSD has a Linux binary compatibility layer: https://www.freebsd.org/doc/handbook/linuxemu.html , but I guess we don't have this ports collection with maintainers by accident. Is there any reason ArrayFire would not work on FreeBSD, or is there anyone who tried it on FreeBSD?

**Comment by 9prady9** [comment]
Based on whats written the FreeBSD URL shared by you, I would expect ArrayFire to work just fine on FreeBSD, at least the CPU backend. CUDA and OpenCL backends functionality would depend on the fact that if there are vendors who provide devices and respective OpenCL implementations for that distribution.

As far as OpenCL link you shared, if you meant to ask if ArrayFire would work with OpenCL 3.0. Though we haven't tested that I would think the answer is a yes since OpenCL 3.0 is essentially OpenCL 1.2 and our OpenCL backend uses that version implementations.

@umar456 Any inputs about ArrayFire FreeBSD ?

**Comment by inf3rno** [comment]
@9prady9 Meanwhile I got the info that Nvidia OpenCL implementation is based on CUDA and since FreeBSD's Nvidia driver does not support CUDA, it won't work no matter how I try. I'll try it on a Linux later. Thanks!
