### ISSUE TITLE
ArrayFire convolution issue with Cuda backend.

### ISSUE THREAD

**Issue by danperrett** [arrayfire/arrayfire#3100]
Hi All,
    I've been having an issue with a certain function call in the 
dphaseWeighted = af::convolve(dphaseWeighted, m_slowTimeFilter);
which seem to produce nothing but nan's.

The back ground is we have recently switched from using AF OpenCL to AF Cuda and the problem that we are seeing happens in the function.
dphaseWeighted = af::convolve(dphaseWeighted, m_slowTimeFilter);

This seems to work well when using OpenCL.

Unfortunatley I can't give you the whole function because of IP. only a couple of snippets.

This convolve lies deep with in a phase extract piece of code. and is actualy the second part of that code which uses the af::convolve funtion.
The first function seems to behave as expected, with sensible floating point data out.
but then when it comes to the second function all I'm seeing is nan's coming out ( I view that with af_print amd dumping the data to a file.

Has anyone experience any think like this before?

Thanks.
Dan

**Comment by 9prady9** [comment]
That is interesting.

Given that our unit tests haven't reported any such inconsistent behavior across backends, I highly doubt it is code bug. However, I won't flatly say there zero possibility of a bug.

It is alright even if you cannot share the exact code. We could use a standalone snippet that reproduce this inconsistent behavior reliably on our end. Creating such a snippet also often helps you narrow down the issue to specific sections of code whether it is happening in ArrayFire function call or otherwise.

If your intention was to actually check with other users of ArrayFire, you should also post to our other community communication channels
- [google forums](https://groups.google.com/forum/#!forum/arrayfire-users)
- [slack](https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ)

**Comment by 9prady9** [comment]
Closing the issue as it has been inactive for a while now. @danperrett Once you have a standalone code snippet that can help us reproduce the problem, kindly reopen the issue with relevant info. Thank you.
