### ISSUE TITLE
'untile' function

### ISSUE THREAD

**Issue by errata-c** [arrayfire/arrayfire#3113]
This is a fairly simple request, I would have use for a `untile` function similar in semantics to the wrap/unwrap functions (as in being inverses of each other). Specifically I'm talking about a function with signature `AFAPI array untile(const array &in, const dim4 &dims)` or
`AFAPI array untile(const array &in, const unsigned x, const unsigned y=1, const unsigned z=1, const unsigned w=1)` that just reverses the tile function by summing the tiles back together. This is possible to do with the `sum` function when tiling a dimension with original size of 1, but more complicated for dimensions larger than that. This would be useful (for me at least) because it would make back-propagation with custom tiled or batched arrays much easier.

I image such a function would be pretty easy to implement, but I don't know enough about cuda or opencl to do it myself.

**Comment by 9prady9** [comment]
@errata-c I believe this should be already achievable using our indexing feature - https://arrayfire.org/docs/indexing.htm Have you looked into it ?

**Comment by errata-c** [comment]
I think the indexing functions can achieve this, but it seems like it would require a more sequential approach. For example, if you had a one dimensional array:
```
[1, 2, 3]
```
and tiled it along that same dimension some number of times:
```
[1, 2, 3, 1, 2, 3, 1, 2, 3... ]
```
then to untile it you would have to access each tiled region one by one to sum them since the  `seq` object will only allow strides between each element instead of groups of elements.
```cpp
array sum = constant(result_dims, 0);
for(int i = 0; i < N; ++i) {
  int start = i * size;
  int end = start + size - 1;
  sum += A(seq(start, end));
}
```
My main worry was the sequential nature of this, since the docs stress avoiding sequential operations for performance reasons.

**Comment by 9prady9** [comment]
True, sequential loops with sequencing kind of defeats the reason why someone might want to use GPU.

While I understand the problem with the code snippet you shared. But I am failing to see use case of this functionality, because tile creates copies of the array along a given dimension. So, to access the original copy, you only need to index that particular range along the given dimension like the following
```c++
array a = randu(5, 1, 2); // 5 x 1 x 2 3d-array
array b = tile(a, 5, 3, 2); // 5x 3 x 2 where second dimension has same values along that dimension
array c = b(span, seq(0, a.dims()[0]-1, 1), span, span); // Isn't this untile essentially ?
```
I am just trying to gather an idea around use of such an explicit function instead of using existing functions. I can also think of a way to use scan by key to achieve the code snippet you shared.

**Comment by errata-c** [comment]
The primary reason I want this function would be for auto-differentiation and backpropagation. So given some input, I'd tile it so it distributes to multiple sets of nodes. Then after inference I'd have to multiply those tiled inputs by the derivative of the activation, and then 'untile' to calculate the next partial derivative for further backpropagation to the previous layer. This function would be very convenient for that purpose, but I know I can find some workarounds if you believe its not worth implementing.

**Comment by 9prady9** [comment]
If a custom implementation is more efficient, we are always up for it. But we need to run some benchmarks with work-around methods and check the performance. Hence, I asked if you looked into alternative approach.

Based on your explanation, you have to un-tile(fetch individual patches) after it is multiplied i.e. it is different array of values altogether to put simply. What do you want to do exactly to each of those patches ? Availability of a alternative to an explicit function will depend on the operations you are doing on this `tiledInput * derivateOfActivation` output. If you are summing up the multiplication results of respective tile patch, then we can achieve that using scanByKey easily. If it(operation) is anything else, kindly elaborate on it so that we can try alternatives or work on custom implementation accordingly.

**Comment by errata-c** [comment]
The operation is simply the summing of those patches, undoing the tile in essentially the same way the wrap function undos the unwrap function.   For scanByKey what would the best way to generate the key values so that they achieve the desired results? Would it be a one time sequential generation, and just reuse the key array?

**Comment by 9prady9** [comment]
Yeah, for that kind of operation, you can definitely use scanByKey. In your case, all values in each path will have same key. For example, if I have 5 patches with 5 values each, you will do something like below to get the keys array

```c++
        array a = iota(dim4(1, 5), dim4(5, 1));
        array b = flat(a); // Doing flat as this would used as key array, this won't allocate new memory
        af_print(b);
```
```
b
[25 1 1 1]
    0.0000 
    0.0000 
    0.0000 
    0.0000 
    0.0000 
    1.0000 
    1.0000 
    1.0000 
    1.0000 
    1.0000 
    2.0000 
    2.0000 
    2.0000 
    2.0000 
    2.0000 
    3.0000 
    3.0000 
    3.0000 
    3.0000 
    3.0000 
    4.0000 
    4.0000 
    4.0000 
    4.0000 
    4.0000 
```

**Comment by willyborn** [comment]
@errata-c 

In case you want to have the striding per group, you can achieve this by adding a dimension in your array.

Perhaps the code snippet below can be helpful?
```
    const int copies = 4;
    
    // Arrays limited to 3 dimensions, since 4th dim holds the # of copies
    af::array A = af::randu(af::dim4(2, 5, 1));
    af::array Tiled = af::tile(A, af::dim4(1, 1, 1, copies));
    af::array UnTiled = af::sum(Tiled, 3) / Tiled.dims().dims[3];

    af_print(A);
    af_print(Tiled);
    af_print(af::sum(Tiled, 3));
    af_print(UnTiled);
```


Dimension 4 is added, containing the number of copies, which gives you new possibilities.

- In case you want to temporarily carve out the array for model 0, and perform an operation:
```
    af::array model0 = Tiled(af::span,af::span,af::span,0);
    model0 += A;
    ...
    Tiled(af::span,af::span,af::span,0) = model0;
```

- In case you want to operate directly on 1 model inside Tiled:
```
    Tiled(af::span,af::span,af::span,0) += A;
```

- In case you want to operate directly on all models at once (in parallel):
```
    gfor(af::seq s) Tiled += A;
```

**Comment by errata-c** [comment]
Thank you, I ended up using the suggestion by @willyborn.
