### ISSUE TITLE
Any plans on Metal 2 support? 

### ISSUE THREAD

**Issue by atolkachiov** [arrayfire/arrayfire#3123]
As OpenCL is deprecated by Apple, and Metal provides [up to 40% performance boost](https://blog.neatvideo.com/post/metal-opencl) compared to OpenCL, 
I wonder if there are any plans on supporting Metal backend?

**Comment by BA8F0D39** [comment]
@atolkachiov 
Metal is obsolete because the last stable release was on 2019 and it only works on Apple ecosystems. Windows, Linux, Android are all unsupported because the licence is proprietary. Furthermore, Metal only targets GPUs and the CPU is not utilized at all.


Vulkan Compute is the true successor to OpenCL, developed by Khronos Group. It gives better performance than Metal and OpenCL on GPU and CPUs. There are multiple Vulkan GPU implementations for machine learning already.
https://github.com/EthicalML/vulkan-kompute

Also there is an experimental CPU implementation of Vulkan
https://www.phoronix.com/scan.php?page=news_item&px=Lavapipe-Teases-Vulkan-1.1

**Comment by atolkachiov** [comment]
@BA8F0D39 are you saying there is no way to effectively use ArrayFire on iOS?

**Comment by BA8F0D39** [comment]
Vulkan compute is available for iOS
https://github.com/KhronosGroup/MoltenVK

Metal is locked to Swift and Objective-C, of which arrayfire doesn't support.

**Comment by 9prady9** [comment]
Hey guys, kindly move the discussion to https://github.com/arrayfire/arrayfire/issues/2878#issuecomment-830767793 as this is a duplicate request. Closing
