### ISSUE TITLE
[Question] How to disable intel mkl?

### ISSUE THREAD

**Issue by twmht** [arrayfire/arrayfire#3201]
Hi,

Can I disable MKL when compiling from source? is mkl a must required package for arrayfire?

thank you

**Comment by twmht** [comment]
i did not see and MKL requirement on the page https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux

**Comment by twmht** [comment]
I find we can use -DAF_COMPUTE_LIBRARY=BLAS to change the backend. the install document needs to be updated.

**Comment by willyborn** [comment]
I changed to vcpkg description file: vcpkg.json (in source dir of arrayfire), so that it now uses openblas and fftw3.  The improvement in speed on non-Intel CPU is remarkable.  Since intel upgraded to OneMKL package, the existing improvement tricks no longer work.

The dependencyies section in the vkpkg.json file now has following content:
```
    "dependencies": [
        "boost-compute",
        "boost-functional",
        "boost-stacktrace",
        {
            "name": "forge",
            "version>=": "1.0.7",
            "platform": "windows"
        },
        "freeimage",
        {
            "name": "fontconfig",
            "platform": "!windows"
        },
        "glad",
        "spdlog",
		"fftw3",
		"openblas"**
    ]
```
PS: intel-mkl is replace by fftw3 and openblas.  The other content can change, depending on updates.
As you can see, this is the windows version, although I expect it to be similar for linux.

I hope this will help you.

**Comment by twmht** [comment]
@willyborn 

I don't use VC for compiling, I just use cmake file to compile, so the config did not work for me.

**Comment by twmht** [comment]
Also, I think it's not ideal if the default backend is set to MKL, since I believe many of the uses did not use intel cpu.

**Comment by 9prady9** [comment]
@twmht The code has Intel-MKL as default backend. You can however use the combination of BLAS/FFTW/LAPACK libaries as well but you need to install them as per instructions on the wiki. Thanks for pointing out about the wiki. I have updated it now.

Note that this defaults to MKL because it is the fastest way to setup all required blas, fftw and lapack dependencies. As mentioned above you can change the cmake option to the other option with all necessary dependencies installed and it should work right away.

**Comment by praisethemoon** [comment]
Hello, I have also came across through this whel building from source on MacOS M1, solved by using BLAS instead, I think the docs should be updated as well, thanks yall!

**Comment by edwinsolisf** [comment]
For future reference, when compiling with CMake you may add specify the libraries used to compile the CPU backend:
```sh
-DAF_COMPUTE_LIBRARY="FFTW/LAPACK/BLAS"
```
or to use Intel MKL:
```sh
-DAF_COMPUTE_LIBRARY="Intel-MKL"
```
additionally, you may need to specify the location of such libraries if they are installed in a non-standard location

We will make sure to update the docs to reflect these as available options for building.

Closing this issue as the question has been answered
