### ISSUE TITLE
[Question] Convolution mode (af_conv_mode) for no padding

### ISSUE THREAD

**Issue by useongkim** [arrayfire/arrayfire#3268]
Before asking a question on github, please consider if it is more appropriate for these other platforms:

* [Slack Chat](https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ)
* [Google Groups](https://groups.google.com/forum/#!forum/arrayfire-users)
* ArrayFire Services:  [Consulting](http://arrayfire.com/consulting/)  |  [Support](http://arrayfire.com/support/)   |  [Training](http://arrayfire.com/training/)

Hi arrayfire,

I have a question about the convolution mode for no padding.

Here is a background of this question.

Suppose I have a rectangular image of which dimensions is [x, y, 1, 1].

I have a filter of which the dimension is [x, 1, 1, 1]

What I want is a simple 1d convolution between the image and the filter along the y-axis without any padding. In my application, convolution result at the image edges is not considered valid value, so I prefer to reduce the output size dimension to contain only the valid values. This will do fewer multiplications and generally help speedup my application (for processing 10^4 orders of images in cpu)

So, the dimension of output I need is [1, y, 1, 1].

But it seems the arrayfire convolution operations support only 2 modes regarding the padding. (AF_CONV_DEFAULT, AF_CONV_EXPEND). The former keeps the output dimensions the same as the input dimensions. The latter will even expand the output demension. Neither shrink the output dimensions.

So, after arrayfire convolution operation, I always get [x, y, 1, 1] or greater.

The questions are
1) Is there a convolution mode that supports the output dimension shrinking by skipping any padding?
2) If there is no such mode, is there any way you can suggest within arrayfire functions capability?

Thank you.

Useong Kim

**Comment by edwinsolisf** [comment]
The operation you are describing is more akin to inner product rather than a convolution. So if your image is `A` and your signal is `B`, then the operation for the output you want can be obtained by the operation `af::matmulTN(B, A)` or `af::matmul(B.T(), A)`. 
ArrayFire does not have shrinking convolution mode, but you can achieve it by using [`af::unwrap` ](https://arrayfire.org/docs/group__image__func__unwrap.htm#gsc.tab=0) to layout the image in a way that by executing a `af::matmul` with the filter you can obtain the convolution you want.
