### ISSUE TITLE
[Question] Will Intel ARC GPUs be supported

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire#3299]
[A770 16GB](https://ark.intel.com/content/www/us/en/ark/products/229151/intel-arc-a770-graphics-16gb.html) supports OpenCL 3.0 and oneapi. 

Will it be supported by Arrayfire?

**Comment by 9prady9** [comment]
I think it should work out of the box since OpenCL 3.0 is just OpenCL 1.2 with all fancy stuff from 2.* marked optional.

If you are looking for oneapi backend, I believe it is on route but it might be a while before full parity is reached w.r.t other existing backends.

Here is the initial effort https://github.com/arrayfire/arrayfire/pull/3296
