### ISSUE TITLE
cuda run out of memory

### ISSUE THREAD

**Issue by Liao-YiHsiu** [arrayfire/arrayfire#336]
I'm not sure it's bug or it's my fault. But when using arrayfire the memory seems to grow up and util it reach the limit, and crash.

Here's the test code:
```
#include<arrayfire.h>
#include<iostream>
#include<vector>
using namespace af;
using namespace std;
int main(){
   vector<array> arr;
   arr.resize(10);
   for(int i = 0; i < 10; i++)
      arr[i] = constant(1, 1000, 10000);
   for(int i = 0; i < 1000000; ++i){
      arr[i%10] = arr[i%10].copy();
      cout << i << endl;
   }
}
```

It seems that 'operator=' is not working correctly (it does not release the memory.)
Waiting to any solution and thank you.

**Comment by pavanky** [comment]
This seems to only affect the CUDA backend. Investigating further.

**Comment by shehzan10** [comment]
I found it crashing on opencl as well when I tested it. 
From my debugging, the memory map size is continually increasing. Somewhere there is memory being created that is not being freed. And it only happens when copy is called. 
This can be observed by printing the memory map size in garbage collector.

**Comment by pavanky** [comment]
@shehzan10 Yeah something weird is happening. On my machine the OpenCL did not crash but the total allocated memory is much greater than the nvidia gpu..

**Comment by pavanky** [comment]
@Liao-YiHsiu This is now fixed in devel.
