### ISSUE TITLE
[Question] about cuda version when installed with exe file

### ISSUE THREAD

**Issue by jcyhcs** [arrayfire/arrayfire#3363]
hi:
i want to install arrayfire wiht binary exe file on windows, then i checkout main webpage, i found 
![image](https://user-images.githubusercontent.com/34532224/218924642-f67e0023-17bd-49a6-9480-8ceee20c1bb1.png)
then i try old version. i found 
![image](https://user-images.githubusercontent.com/34532224/218924761-3d85b18b-10e0-4909-a42d-d008204777eb.png)
BUT!，my cuda version is 11.6, oh, what can i do??
please help me!

**Comment by umar456** [comment]
The version indicated on the installer is the version of CUDA that ArrayFire was built against. You do not need to have CUDA installed on your computer to use ArrayFire. You only need the GPU driver that supports that version. You can find out the required version of the driver you need by looking at the release notes here: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id3

If you are using CUDA independent of ArrayFire in your application then it is better to use the same version of the software. Otherwise you want to use the latest version supported by your hardware. Unless you are using an old Kepler GPU you should go with the latest versions.
