### ISSUE TITLE
Selecting a vector from a multidimensional array

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#341]
I am trying to select a vector from N-D array along one dimension. 
I am confused about using subscript indexing for the purposes.

This code 
```
    // Number of fast time samples
    const unsigned int n1 = 2;
    const unsigned int n2 = 3;
    const unsigned int n3 = 4;
    const unsigned int n4 = 5;

    af::array dpData = af::randu(n1, n2, n3, n4);

    af::array k = dpData(1, 2, af::span, 2);
    std::cout << k.dims() << std::endl;
```
returns
```
2 3 4 5
```
while I am expecting to get 
```
1 1 4 1
```
How can I select a vector along 1 dimension while fixing other subscripts for the array?

**Comment by pavanky** [comment]
@Kerkil 

It is a combination of two bugs. 

- `k.dims()` is printing the wrong values because of the way we are doing lazy evaluation of indexing operatios.
- `dpData` is the wrong size because we did not implement the indexing operator for 4 indices with a combination of ints and sequences. This means C++ is automatically treating `int`s as `seq()` causing issues.

I will try to fix both issues.

For now, can you use the following to resolve your problem ?

```
        array a = randu(2, 3, 4, 5);
        array b = a(seq(1,1), seq(2,2), span, seq(2,2));
        b.eval();
        std::cout << b.dims() << std::endl;
        af_print(b);
```

**Comment by pavanky** [comment]
@Kerkil This is now fixed in devel.
