### ISSUE TITLE
Convolution Issues

### ISSUE THREAD

**Issue by cheesema** [arrayfire/arrayfire#513]
Hi,

I have been playing round with the convolution functions over the last few weeks especially in the context of 3D arrays , and have noticed a few things, that I am not sure are intended or not.

Regarding 1D filters:

Currently you can only iterate over 2D arrays, if you try to do it over a 3D array you get; (Directly using Convolve1)

image_out = convolve1(image_in,filter); where filter is a 1D filter and image_in a 3D array:
``
In function /PHD/APSource/arrayfire/src/api/c/convolve.cpp(64):
Invalid argument at index 1
Expected: (sdims.ndims()<=batchDim)
libc++abi.dylib: terminating with uncaught exception of type af::exception
``

This is also the case when you attempt to use GFOR to batch them.

Question: Additionally, is there a way to convolve the 1D filter across the other dimension rather then transpose the input array before and after?, 

Regarding 2D filters:

Only currently working for square filters. Regardless of the combined length. (I understand there is currently a limit on the total number of points within the convolution filter)

Separable filters, this is also the case, both vectors need to be the same length. 

API:

Regarding the api with Convolve function, I found that I could only get things reliably working the way I wanted when I directly used the convolve1 or convolve2 functions. 

Additionally, I also wrote up a code for doing the convolution using FFT filters of arbitrary size in 2D if anyone is interested, let me know. (Not likely very optimal though) 

Cheers,

**Comment by 9prady9** [comment]
@cheesema 

We have done lot of under the hood changes to how convolve is implemented in 3.0 beta version. 

We have updated the documentation website very recently, can you please check the details on how convolve should behave [here](http://www.arrayfire.com/docs/group__convolve__mat.htm) for various cases.

Regarding your observations, following is the current state of convolve implementation :
- We haven't added GFOR for all the functions yet, convolve is one of them.
- We are yet to add fft based convolution for large filter sizes.
- Which filter size are you trying in 2D ? Currently we support any shaped kernel until filter size 5, and only square filters from 6 to 11. For any other type of kernel shapes, we intend to add fft based convolution very soon(which hasn't been added yet).

Separable filers should work fine, if they are not, it is probably a bug. Can you please share your test code so that we can check it.

Thank you, Pradeep.

**Comment by cheesema** [comment]
Cheers, Will do. I'll report back.

**Comment by 9prady9** [comment]
@cheesema Did you get a chance to look at it again ?

**Comment by cheesema** [comment]
Hi,

Yeah sorry you where right it does seem to be working now for different sizes, not sure what I was doing before. However, the size limit on an individual filter appears to be 32?, I would have thought it would be the same as for the 1D convolution operations (~120)?

Regarding the new documentation for the convolution functions. It seemed to confuse me regarding to the code I currently have running. I am using the convolve1 with 1D filters over a 2D array. This seems to work fine. However from the documentation there seems to be a restriction of an array that is mx4 for the Many to One mode? (However I seem to be running it as mxn)

[m 4 1 1]	[m 1 1 1]	Many to One	Output will be 2d array with 1st dimension length as 4 - 1 filter applied to 4 inputs

It seems like I am missing something :)

Cheers,
Bevan

**Comment by 9prady9** [comment]
@cheesema Yes, we had have different size restrictions for each dimension because of the amount of shared memory that we can allocate for a specific filter size varies with the dimension of the convolution operations, 1d, 2d or 3d. Hence the difference in restrictions.

"[m 4 1 1] [m 1 1 1] Many to One Output will be 2d array with 1st dimension length as 4 - 1 filter applied to 4 inputs" that statement is part of an example that was being described where the 2nd dimension values is 4. Sorry if it caused any confusion. I shall try to make it more conspicuous with some code examples.

Pradeep.
