### ISSUE TITLE
FFTW license incompatible with arrayfire license?

### ISSUE THREAD

**Issue by glehmann** [arrayfire/arrayfire#526]
FFTW is distributed under the GPL, which I believe, doesn't work well with arrayfire's license.

**Comment by pavanky** [comment]
From my understanding, it is OK to link with GPL licensed software. We are not modifying or distributing FFTW.

However there might be an issue where libafcpu and fftw might be concerned as a "single program" since we don't provide alternatives. We can plan to provide alternative libraries to link with (MKL, ffts etc) or make libafcpu without support for FFTs.

**Comment by pavanky** [comment]
Here is a good write up about dynamic linking GPL libraries: http://lwn.net/Articles/548216/

**Comment by shehzan10** [comment]
In PR #657, added capability to use FFTW, ACML and/or MKL. This involves simply changing the FFTW CMake paths. Notes will be added to the wiki.
ArrayFire windows installer will be shipping with either ACML or MKL (TBD).
