### ISSUE TITLE
Expose Free/Total Device Memory

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire#538]
For monitoring purposes it will be useful to get the memory usage on the compute device.

**Comment by pavanky** [comment]
@jramapuram OpenCL does not provide a way to get Free memory, but it does provide a way to query total memory. I am not sure if that will be useful for you.

That being said, over the last couple of hours I have been working to expose ArrayFires memory manager. It provides information about the amount of memory arrayfire has allocated and how much of that is tied down to buffers that are within scope.

Would the function mentioned above be helpful ?

**Comment by jramapuram** [comment]
@pavanky : This would be immensely helpful!

**Comment by pavanky** [comment]
@jramapuram This is already in devel if you want to check it out.

**Comment by jramapuram** [comment]
Looks good @pavanky . To clarify: is alloc_bytes the total allocated bytes? Or is it alloc_bytes * alloc_buffers ?

**Comment by pavanky** [comment]
`alloc_bytes` is the total allocated bytes. `alloc_buffers` is exposed because it represents the size internal data structure. This will enable the user to customize when and how the garbage collection can be called.

By default, garbage collection is called if `alloc_buffers >= 100` or if `used_bytes >= 1GB`. `used_buffers` is exposed to help debug memory leaks.

**Comment by jramapuram** [comment]
Thanks @pavanky ! Appreciate your contributions.
