### ISSUE TITLE
ORB failing on NVIDIA OpenCL backend with exception

### ISSUE THREAD

**Issue by pentschev** [arrayfire/arrayfire#663]
ORB fails on NVIDIA with OpenCL backend. The issue originates in boost.compute sort. The behaviour can be reproduced by running ORB for about 1k times on 1080p images.

The boost.compute file `include/boost/compute/algorithm/detail/radix_sort.hpp` has some hardcoded sort parameters, in specific the parameter `k`, which is currently set to `4`. The remaining part of the code should be able to handle values of `1` and `2` for `k` and when `k` is set to `2`, no exceptions occur. There is no documentation on why the value of `k` is currently fixed to `4`, further analysis is required to identify what is the impact of changing this variable for both performance and correctness.

**Comment by bkloppenborg** [comment]
After running the benchmark suite on several machines with different GPUs and drivers, this bug has become even more mysterious. This issue appears to only impact NVIDIA GPUs; however, it appears to correlate with neither specific hardware nor driver revisions. Here are the results of my tests:

machine | GPU | driver version | result
afw0 | Tesla K20c | 346.59 | fails |
afw0 | Quadro K4000 | 346.59 | **passes** |
romulus | Quadro K4000 | 346.46 | fails |
romulus | Quadro K4000 | 346.87 | fails |
romulus | GTX 780 | 346.46 | **passes** |
romulus | GTX 780 | 346.87 | **passes** |
belle | Tesla K20c (card 1) | 346.46 | fails |
belle | Tesla K20c (card 2) | 346.46 | fails |
belle | Quadro 6000 | 346.46 | fails |
ripley | GTX 750 | 346.46 | fails |

Notice that for the Quadro K4000, the bug occurs in the 346.49 and 346.78 drivers, but not the 346.59 driver. Also notice that the bug is encountered on some GPUs, but not others (e.g. the GTX 780 and K4000 on Romulus).

The change @pentschev mentioned above does indeed resolve the issue. @kylelutz , what does changing `k=4` to `k=2` in the radix sort code do? Is this a bug in boost compute?

**Comment by pavanky** [comment]
@bkloppenborg We depend on a particular version of boost compute. Can you change the tag in `build_boost_compute.cmake` to master and devel to see if the problem still persists.

**Comment by bkloppenborg** [comment]
Using the current git master (9b3965878d87505ce4399a996b44fe39) of boost compute and the plot thickens

machine | GPU | driver | version | benchmark | arrayfire tests
--- | --- | --- | --- | ---
afw0 | Quadro K4000 | 346.59 | failed on 4k images | passed
afw0 | Tesla K20c | 346.59 | failed on 4k images | passed
afw1 | HD 7970 | N/A | passed | failed (see below)
belle | Quadro 6000 | 346.46 | passed | passed
belle | K20c | 346.46 | passed | passed
ripley | K40c | 346.46 | failed on 4k images | passed

**Comment by pavanky** [comment]
Failures on `afw1` are occurring on non modified arrayfire as well. Could be a driver issue. Other AMD GPUs are running fine (patton - S10000, bender - AMD A10 APU)

**Comment by kylelutz** [comment]
The `k` parameter for the radix-sort algorithm dictates how many bits of each value we sort per pass. Setting `k` to `2` will use less memory in each work-group, but result in double the number of sort passes which could have a negative effect on performance. The current version of Boost.Compute allows tuning this parameter per-device, but, like you said, the default value (if no tuning is loaded) is `4`.

However, I'm surprised to see this passing/failing depending on driver versions. Can you give me some more details on how it fails? Does it crash, or are the numbers just incorrectly sorted (or corrupted)?

**Comment by shehzan10** [comment]
Can we revisit this and verify whether this is still an issue?

**Comment by pavanky** [comment]
move it to be resolved later

**Comment by bkloppenborg** [comment]
@shehzan10 I caught this in the benchmark suite. I don't think we've seen this error for some time now. Unless you have seen it, I think we can close this issue.

**Comment by shehzan10** [comment]
I remember Peter showing me a case where it was still failing. I can't remember the reproduction of that so can't verify it being resolved.
Im fine with closing this issue until we get a more concrete bug report.

**Comment by 9prady9** [comment]
@arrayfire/core-devel Is this still an issue ?

**Comment by pavanky** [comment]
Closing this. We can open if someone complains.
