### ISSUE TITLE
extremely slow on gpu   (running the helloworld example with opencl)

### ISSUE THREAD

**Issue by xumbu** [arrayfire/arrayfire#687]
Hi.

I saw your Webinar on AMDs YT Channel yesterday and think arrayfire could be a great library for my linear algebra stuff. 

I started checking out the examples... But most examples are surprisingly slow when I use OpenCL.

When I run it on my CPU (i5) it finishes almost immediately.
With OpenCL it takes a few seconds!

GPU: AMD Radeon R9 280
OS: Windows 10

When I loop the complete function, OpenCL is actually much faster... except for the first iteration.
I thought the reason could be some slow memory allocation on GPUs (I dont have much background knowledge about hardware) but the bottleneck seems to be the matrix operations

**Comment by pavanky** [comment]
@xumbu The OpenCL backend compiles the kernels during the first run. In our experience the AMD OpenCL driver takes longer than other platforms to compile the kernels. Due to the nature of OpenCL, we can not ship pre-compiled kernels (this would mean we are limiting the hardware we support).

For long running algorithms this should not be a problem because ArrayFire caches the necessary kernels after the first time it sees a kernel.

**Comment by xumbu** [comment]
Good to know. :)
I was just surprised. 

Thanks for your fast response!
