### ISSUE TITLE
Memory leak in indexing

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#693]
```
for (;;)
    {
        const size_t nrows = 100000;
        array A = randu(nrows);


        array vals, inds;
        sort(vals, inds, A);

        array bottoms = constant(0, nrows);
        bottoms(af::seq(0, 1000)) = 1;
    }
```

**Comment by pavanky** [comment]
Reproduced using cpu backend.

**Comment by munnybearz** [comment]
The seq memory leak is fixed, but the array usage one still leaks:

```
    for (;;)
    {
        const size_t nrows = 1000000;
        array A = randu(nrows);

        array vals, inds;
        sort(vals, inds, A);

        af::index bottomInds = af::index( inds.rows(0, 1000) );
        array bottoms = constant(0, nrows);
        bottoms(bottomInds) = 1;
    }
```

**Comment by munnybearz** [comment]
I think I see why this memory leak is happening. I think the weak copy semantics are wrong in af_weak_copy.

**api/cpp/index.cpp**
```
index::index(const af::array& idx0) {
    array idx = idx0.isbool() ? where(idx0) : idx0;
    af_array arr = 0;
    AF_THROW(af_weak_copy(&arr, idx.get()));
    impl.idx.arr = arr;

    impl.isSeq = false;
    impl.isBatch = false;
}
```

Currently the weak copy does this:

**api/c/data.cpp**
```
template<typename T>
static af_array weakCopyHandle(const af_array in)
{
    detail::Array<T> *A = reinterpret_cast<detail::Array<T> *>(in);
    detail::Array<T> *out = detail::initArray<T>();
    *out= *A;
    return reinterpret_cast<af_array>(out);
}
```

I believe there are 2 problems here.

First, it is not a weak copy because of this line:
```
    *out= *A;
```
This ends up copying the shared_ptr to the data in the underlying Array object. So now the index is a shared owner of the data of the array and prevents it from being deleted when the other owners have been destroyed. I think this needs to be redesigned with the inclusion of std::weak_ptr

Second, initArray() calls new. Further up the stack the af_array is stored in the index object, but delete / af_destroy_array is never called on it. When the index object gets deleted the af_array pointer is just cleared and the underlying Array object was not deleted. I guess this was intentional because it assumed the weak copy did work and so there is no need to delete the underlying object, but right now it is causing a memory leak. I've temporarily patched this on my branch (https://github.com/munnybearz/arrayfire/commit/e70bbaf0ed3920dca41a7b99300af050c58a8dd6) by making a destructor for the index object and calling af_destroy_array(). It has fixed the memory leak but it is not a good solution (eg. doesn't delete the af_array when an index object that uses the seq member of the union is assigned to it).


I've now found another leak when using the array operator(). This code shows the issue, which leaks even with my patch above:

```
for (;;)
{
    const size_t nrows = 1000000;
    array A = randu(nrows);

    array vals, inds;
    sort(vals, inds, A);

    array upper(where(A > 0.5));    // Leaks about 1MB/s
    if (upper.dims(0) > 0)
        A(upper) = Inf;             // Leaks about 5-10MB/s
}
```

**Comment by pavanky** [comment]
@munnybearz Your commit is the proper fix for the issue. The internal behavior is working as expected. The naming of the function is a bit confusing. We should perhaps have called it `af_shared_copy` instead of `af_weak_copy`. I think we will change the name to reflect this. 

The problems you are seeing started occurring recently because of the proxy class we introduced to clean up a lot of kludge in the indexing code. However this resulted in a few regressions that we are actively trying to resolve. 

Thank you for digging into the code base and providing us with valuable feedback. If you can send in a pull request for the original issue that would be great.

**Comment by munnybearz** [comment]
ahh I see! ok thanks for the explanation, that makes sense. 

PR #699 created

**Comment by pavanky** [comment]
@munnybearz I ran it for a couple of minutes using the cpu backend and monitored the usage. The memory spikes a bit initially (probably because the memory manager is allocating new buffers because of `where(A > 0.5);` is generating arrays of different sizes. It does get stable after a few seconds though.

**Comment by munnybearz** [comment]
Hi Pavan. Thanks very much for fixing this :+1: . I'll let you know if I find any more :-)

**Comment by pavanky** [comment]
This fix was all @umar456.
