### ISSUE TITLE
complex support for mathematical functions

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#769]
- trigonometric functions
- exponential functions

**Comment by Godisemo** [comment]
This is a list of all functions from the standard C complex.h header. I think it would be nice to have all of these implemented in ArrayFire as well. Maybe I can get some help to fill in which functions already exists? I could probably help out with implementing a few of these, but since I'm not very familiar with the ArrayFire internals i need some quick guidance to get started.

- [ ] `double               cabs(double complex);`
- [ ] `double complex       cacos(double complex);`
- [ ] `double complex       cacosh(double complex);`
- [ ] `double               carg(double complex);`
- [ ] `double complex       casin(double complex);`
- [ ] `double complex       casinh(double complex);`
- [ ] `double complex       catan(double complex);`
- [ ] `double complex       catanh(double complex);`
- [ ] `double complex       ccos(double complex);`
- [ ] `double complex       ccosh(double complex);`
- [ ] `double complex       cexp(double complex);`
- [ ] `double               cimag(double complex);`
- [ ] `double complex       clog(double complex);`
- [ ] `double complex       conj(double complex);`
- [ ] `double complex       cpow(double complex, double complex);`
- [ ] `double complex       cproj(double complex);`
- [ ] `double               creal(double complex);`
- [ ] `double complex       csin(double complex);`
- [ ] `double complex       csinh(double complex);`
- [ ] `double complex       csqrt(double complex);`
- [ ] `double complex       ctan(double complex);`
- [ ] `double complex       ctanh(double complex);`

**Comment by pavanky** [comment]
@Godisemo thanks for creating a comprehensive list! I checked some of the functions that are already supported. Thanks for the offer of helping out, but I think it is easiest if I pushed all of these in myself for now :) It'll only take me a couple of hours to implement them. 

The reason it hasn't been added so far is because our development is usually request based. And your request pushed it up in our priority list!

**Comment by Godisemo** [comment]
Ok, great! Looking forward to the list being completed. 😃

**Comment by pavanky** [comment]
@Godisemo If you have some time, can you ping me on our gitter channel ? https://gitter.im/arrayfire/arrayfire

**Comment by pavanky** [comment]
I realized that there's a reference function for [exp](https://github.com/arrayfire/arrayfire/blob/devel/src/api/c/unary.cpp#L108) already implemented.
 
@Godisemo offered to help us out with this following the reference :)

**Comment by Godisemo** [comment]
I added code for sqrt and log in PR https://github.com/arrayfire/arrayfire/pull/1466 but since I can't manage to compile it on my computer it is untested. Could you test it for me before I continue?

**Comment by pavanky** [comment]
@Godisemo looks like `arg` is done but is not checked over here. Or is it a case of `carg` doing something different than what `arg` does in arrayfire?

**Comment by Godisemo** [comment]
Yes, I thought I checked that one earlier. I might want to write a templated version though, to help clean up the code a bit.

**Comment by Godisemo** [comment]
I have added code for all but two of the functions now, `cpow`which is not unary and `cproj` which I don't really understand.

What remains is writing tests, and some code cleanup. I think there might be room for simple optimizations as well.
