### ISSUE TITLE
Illegal casting

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#816]
Hi,

The code for [`getInfo()`](https://github.com/arrayfire/arrayfire/blob/master/src/backend/ArrayInfo.cpp#L30) seems to lead to undefined behaviour:
```
const ArrayInfo *info = static_cast<ArrayInfo*>(reinterpret_cast<void *>(arr));
```
as arr is of type af_array which is a pointer to a type derived from ArrayInfo.
Check http://stackoverflow.com/a/5445220.

**Comment by pavanky** [comment]
I think the problem only when multiple inheritance is in play. The SO answer deals with such a case. This should not be a problem in our case. 

@umar456 any thoughts?

**Comment by umar456** [comment]
I can see this being a problem with multiple inheritance but since we only have one base type it is a standard upcast which is safe in C++. I don't think we even need the `reinterpret_cast` in this case. The `static_cast` should be able to handle the conversion. This has been tested on multiple compilers(msvc, clang++, g++, icc) and we haven't run into any issues.
