### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by jas99** [arrayfire/arrayfire#825]
Do you guys support arrrayfire on android devices?

**Comment by 9prady9** [comment]
@jas99  We did have Android specific binaries in ArrayFire 2.1. However, 3.0 hasn't been tested on Android platform yet, but we do have plans to do it in the future.

**Comment by jas99** [comment]
@9prady9 That was hell of quick response. Nice to know that; is it low pirority. 
And when you say future whats your gut felling; near or far future.

Thx

**Comment by 9prady9** [comment]
@jas99 Glad to be of help. It is on lower side of priority in terms of near future(next couple of months). We want to iron out any bugs in the library and add some additional features such as thread safety etc. and then try it out on Android platform.
@pavanky Do you want to add anything else ?

**Comment by pavanky** [comment]
@jas99 There are multiple ways ArrayFire can be supported on Android. 

- We can support NEON-accelerated version of our CPU backend.  
- We can support OpenCL accelerated versions for GPUs.
- We can build a new backend on top of renderscript.

The 2.1 version @9prady9  mentioned used OpenCL.

That said, OpenCL on Android is tricky because not all manufacturers ship OpenCL libraries on their phones. And even those that do, they do not support it on all their devices. So if we go the OpenCL route it should be done in a couple of months, but it will not support all OpenCL devices.

Neon acceleration will take a few months (not because it is complicated, but because we have other things in our pipeline).

Renderscript support will take longer because it involves creating an entirely new backend.

**Comment by jas99** [comment]
@9prady9 @pavanky Thx guys for the prompt responses. Really helps clear things up.

**Comment by csarron** [comment]
Any updates on Android support?

**Comment by 9prady9** [comment]
@csarron As of now, there is no android support yet. As soon as we have a beta-ready support for android platform, we shall make sure to inform the community about it.
