### ISSUE TITLE
Possibly unnecessary include in cpu backend

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#828]
Is this line:

```
INCLUDE("${CMAKE_MODULE_PATH}/FindGLEWmx.cmake")
```

needed in L34 of `src/backend/cpu/CMakeLists.txt`?

The CPU backend of `v3.0.0` used to build fine. `v3.0.1` now requires OpenGL due to the presence of this line. I commented it and the package built fine, which makes me question its utility.

EDIT: missing punctuation

**Comment by shehzan10** [comment]
The line you mention, I remember removing it via https://github.com/arrayfire/arrayfire/commit/829ddcb783b7fe58888391ee48b43aff067309f4#diff-3c4bf77faa47ca50746b12d0fdde2d0fL13. I'm not quite sure how it made its way back into the code.

It is redundant since we set the include files in the main CMakeList.
Do you want to send in a PR for this?

**Comment by ghisvail** [comment]
I will

**Comment by pavanky** [comment]
@shehzan10 looks like it was reintroduced during a merge. Perhaps an incorrectly done merge conflict resolution.

**Comment by shehzan10** [comment]
Yeah that's what I assumed happened.
