### ISSUE TITLE
SVD for all backends

### ISSUE THREAD

**Issue by paoloviviani** [arrayfire/arrayfire#862]
Do you plan to implement the Singular Value Decomposition based on cuSolver anytime soon?
Thanks!

**Comment by pavanky** [comment]
@paoloviviani Our first attempt was to support the basic matrix factorizations. We will try to support SVD by the 3.1 release if everything goes according to plan.

**Comment by paoloviviani** [comment]
Thanks! do you have a roadmap for the release of the next versions?

**Comment by pavanky** [comment]
You can look at our milestones page: https://github.com/arrayfire/arrayfire/milestones
Here is a blog post describing our release cycles: http://arrayfire.com/arrayfire-release-cycle/

Right now we have set 3.1 for the end of July / early August.

**Comment by paoloviviani** [comment]
Great, thanks!

**Comment by klemmster** [comment]
Hey,

integrating cuSolvers SVD, I've stumbled over "Remak 1: **gesvd** only supports m>=n" (as well as remark 2, but that's just an annoyance, not a problem)
The problem I'm trying to solve has m<n, so I won't polish my implementation. If anyone is interested in it, I've uploaded the (working, but not thorowly tested code [here](https://github.com/klemmster/arrayfire/tree/cusolver_svd)

Sorry for the code reformatting, but arrayfires and clang-formats interpretation of google code style seem quite different.

**Comment by pavanky** [comment]
@klemmster That is a great start! Can you send in a PR to `svd` branch here after the following fixes:

- I made a comment that needs fixing in the CUDA backend.
- Can you also add stumps for OpenCL backend ? Right now the CPU and OpenCL backend erroring out with the following exceptions is good enough. `CPU_NOT_SUPPORTED()` and `OPENCL_NOT_SUPPORTED()`
- The code style is not a blocker for us as long as it is reasonably close.

Another thing to note for the future is about commit messages. Instead of having something like `Add CPU stump`, it might be better to have `Add CPU stump for SVD`.

**Comment by pavanky** [comment]
Now that is out of the way, lets talk about supporting `m < n`.

From what I understand, the following property holds true.

if `u`, `s`, `vt` are the decomposition of `a`, the decompositions of `transpose(a)` will be `vt`, `transpose(s)` and `u`.

You can then use this property to support `m < n` internally.

**Comment by klemmster** [comment]
@pavanky Wow, I didn't really expect any feedback to my message, let alone a review of the code! Expect a PR soon.

Regarding the math: Do'h!. Of course, thanks for taking the time to jot that down for me!
