### ISSUE TITLE
Mean computation overflows

### ISSUE THREAD

**Issue by alcinos** [arrayfire/arrayfire#884]
When the sum of the array doesn't fit in the target datatype (even if the mean does)
See #883 for relevant tests

**Comment by pavanky** [comment]
This might be a bigger problem to address than a simple change to `mean`. The problem likely occurs because the function the reduction function keeps the running sum in the same datatype as the input (in case of floating point numbers) causing the overall overflow errors.

I think the best way to deal with this without breaking ABI and API from 3.0 release would be to leave the default behavior as is and have another function extending the [fixes already made for sum of nan](https://github.com/arrayfire/arrayfire/issues/860).

Then `mean` can either have an alternative API that can be called when more precise calculations are needed as well.

**Comment by alcinos** [comment]
Maybe it is more of an algorithmic problem (the sum + division is maybe not the best way to compute the mean)? The problem can indeed be easily solved for small datatypes (char, uchar,…) by computing the sum in "bigger" datatypes. But this doesn't work if the datatype is already the biggest available (double)…
This post http://stackoverflow.com/questions/571986/finding-mean-of-array-of-ints discusses way of computing the mean in an overflow-safe way

**Comment by pavanky** [comment]
@alcinos That algorithm does not look like it is parallelizeable

**Comment by pavanky** [comment]
Hmm on second thought it could be. I need to think a little bit more about this.

**Comment by umar456** [comment]
fixed via #1849
