### ISSUE TITLE
Make sure all backends are thread safe

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#907]
Hi team,

Currently I'm saturating my GPU, which is cool. But on the same server I can have more GPU's - eg. an Amazon g2.8xlarge instance has 4 Nvidia K520's. I want to be able to use them too.

I want to be able to launch 4 threads and allocate each one a GPU for them to work on. I was reading the documentation for cudaSetDevice() and I believe it is possible to do this, but I think it requires some work on the ArrayFire memory manager and device manager. I really want to be able to do something like this:

```
Main thread
(launch # of gpu's of std::threads, eg. 4 threads)

Worker thread
af::setDevice(threadID);       // threadID is 0-3, passed in as a parameter by the main thread
```

Then the rest of the worker thread uses the GPU for the device id it set.

The traditional solution of a cluster of GPU hosts would be ideal, but I'm processing huge amounts of data very fast and distributing the work to multiple hosts adds too much latency. There's just too much data to serialise, transfer and deserialise to make the calculation worthwhile on a cluster. So it needs to be done on the same server. 

Currently my only alternative is creating multiple processes o the server each having their dedicated GPU and having 1 coordinator process managing the work and shared memory for the data structures. It can be massively simplified if ArrayFire could support multiple GPU's used through dedicated threads.

Please could you add this to the library?

**Comment by pavanky** [comment]
@munnybearz We are trying to make the library thread safe. Once this is done, we'll have an example demonstrating what you request.

**Comment by munnybearz** [comment]
Awesome I'm really looking forward to that then!!

**Comment by vakopian** [comment]
@pavanky @9prady9 As this issue has been pushed from milestone to milestone for more than a year now, I was wandering if an ***intermediate*** solution that just uses a global mutex around the thread-unsafe parts of the library (or even around *all* `af_***` functions) could be implemented quickly. 
Even if the locking is very coarse-grained and crude, this would at least allow to safely run arrayfire code in multi-threaded programs.

**Comment by pavanky** [comment]
@vakopian What backend are you most interested in ?

**Comment by vakopian** [comment]
@pavanky 
eventually cuda, but before I port everything to arrayfire, my current code is a mixture of cpu and arrayfire (with either cpu or OpenCL-cpu back-end). Is any of the back-ends thread safe currently?

**Comment by pavanky** [comment]
@vakopian cpu backend is closest to being thread safe, but I am not entirely sure. There are major issues with CUDA and OpenCL being threadsafe.

**Comment by vakopian** [comment]
@pavanky is there a separate branch where this development is being done? Perhaps I can contribute

**Comment by pavanky** [comment]
@vakopian I have created a branch under my fork: https://github.com/pavanky/arrayfire/tree/thread-safe

Right now this is just a branch from devel. I'll begin some work over the weekend. In the meantime, can you do some testing on the CPU backend in a multi threaded environment and report back if there are any issues ?

**Comment by pavanky** [comment]
In this comment I will be noting down some blockers for thread safety. The work can be distributed to people as necessary. 

[ ] Have one "manager" per backend. This will reduce the number of locations static variables are defined.
[ ] Locking / Unlocking memory in memory manager when using multiple threads (possibly through a stand alone thread for memory management).
[ ] Just in time compilation for CUDA and OpenCL (consider sharing compiled binaries across threads 
 vs each thread having it's own store).

I'll update as we find new issues.

**Comment by vakopian** [comment]
@pavanky just trying to check my understanding of the current code for the CPU back-end. Is it true that the current CPU back-end is essentially hard-coded to be single-threaded? Here is how I came to this conclusion:
1) all AF functions get "queued" before being executed. The number of queues is currently hard-coded to `1`: [platform.cpp:301](https://github.com/arrayfire/arrayfire/blob/devel/src/backend/cpu/platform.cpp#L301)
2) A queue is running in its own (single) thread: [async_queue.hpp:25](https://github.com/alltheflops/threads/blob/5e778ce0a7f0f80af9d32ea3569df3dbec834f59/async_queue.hpp#L25). 
3) This one thread (in `async_queue`) is in charge of both listening to queue events [async_queue.hpp:39](https://github.com/alltheflops/threads/blob/5e778ce0a7f0f80af9d32ea3569df3dbec834f59/async_queue.hpp#L39), and also for executing the functions that are pushed into the queue [async_queue.hpp:50](https://github.com/alltheflops/threads/blob/5e778ce0a7f0f80af9d32ea3569df3dbec834f59/async_queue.hpp#L50)

Thus, we have a single queue, that's running a single thread and all functions are siphoned through it.
I also see this in practice: when I run a few long operations in multiple queues, I don't see any real concurrency.
So is my understanding correct?

**Comment by pavanky** [comment]
@vakopian Yes, the CPU backend is asynchronous at the moment (i.e. the host thread is free to do other things), but the enqueued operations are done sequentially (first in first out).

**Comment by vakopian** [comment]
@pavanky So if I'm not mistaken the `queue`, `async_queue` and the related code is basically trying to implement a thread pool, right? If that's indeed the case, perhaps this (single header) [ThreadPool library](https://github.com/Youka/ThreadPool) could be used instead? I think it's the same ideas and even similar implementation, but in a cleaner and more self-contained class.

Another thing I wanted to note here (since you mentioned static variables), I just learned recently that the ***scoped*** static variables are actually thread-safe in C++11 (as opposed to older versions of the standard). AF has lots of those in many places, but if we compile with C++11, those don't need to be fixed anymore.

**Comment by pavanky** [comment]
@umar456 is in charge of the threadpool. Umar any thoughts ?

@vakopian 
The idea was to have a multi threaded cpu backend eventually. But for now it is single threaded.

As for scoped static variables being thread safe,  that will make things a lot easier. However I think we still have a couple of places which use global statics. Though these can be moved into a function that returns the static variable.

@arrayfire/core-devel What are your thoughts on moving all backends to C++-11 (including CUDA). I think CUDA supports C++11 since CUDA 7.0 which makes things easier. Alternatively we can have it so just the `.cpp` files have the static variables and just compile the `.cpp` files with C++11 (like we do right now).

**Comment by pavanky** [comment]
stackoverflow post talking about scoped static variables: 
http://stackoverflow.com/questions/8102125/is-local-static-variable-initialization-thread-safe-in-c11

**Comment by pavanky** [comment]
btw VS 2013 does not support this feature: https://msdn.microsoft.com/en-us/library/hh567368(v=vs.120).aspx.  Look under the section called "magic static". 

GCC and CLANG (unless Apple dropped it) seem to support it. 
VS 2015 also supports it: https://msdn.microsoft.com/en-us/library/hh409293.aspx

**Comment by umar456** [comment]
The C++11 standard says that the initialization of magic statics are thread safe. The access and modifications are not.

I fail to see the advantages of the ThreadPool library over the async_queue class. It seems to be a reimplementation of the std::async class. Just like std::async the ThreadPool returns std::futures every time something is queued. This would mean that we will need to keep track of these futures otherwise the operation will be synchronous. If we are keeping track of these futures then we will have another singleton container that will need to be locked every time something is enqueued. Also it looks like it is processing each command on the first available thread. This would mean that we would have to implement a method to define dependencies between operations.

The async_queue class was created to mimic the behavior of command queues in OpenCL and streams in CUDA. We can add concurrency by creating multiple async_queues and queueing tasks based on the thread_id or some other mechanism.

This is also a difficult problem because ArrayFire is essentially a parallelism library meaning that we want all of the CPU resources to be working on one task then another; similar to the OpenCL and CUDA backends. Users using ArrayFire in concurrent threads may hurt performance because each task assumes it has full control of the hardware.

We need ArrayFire to be thread safe in that you should be able to access the arrays from multiple threads. Users should not try to use threads in their code to improve performance by running the same operation on two threads. Tasks should be parallelized to use all of the compute resources of the CPU to speed computations. I have some ideas on how to do something like this but that is not related to this issue.

**Comment by WilliamTambellini** [comment]
Good morning gentlemen, 
Is this issue/item likely to be in 3.4.2 or is it really for 3.5 ?
Kindly

**Comment by pavanky** [comment]
@WilliamTambellini I am not sure if this is possible in the timframe of 3.4.2

**Comment by vakopian** [comment]
> Users should not try to use threads in their code to improve performance by running the same operation on two threads.

I understand what motivates the statement above, but I think it might be missing 2 important scenarios:

1) Hybrid applications that are very "parallelizable". By "hybrid", I mean applications that do lots of CPU calculations, then lots of GPU (ArrayFire), then more CPU, then more GPU, etc. And by "parallelizable", I mean it can benefit from concurrency not just from GPU, but at CPU level as well. A simple example would be an image processing algorithm that can easily be parallelized by splitting it into tiles and each tile needs both CPU and GPU processing. For such an application, not using threads means not taking advantage of the CPU for some tiles while the GPU is busy processing the other tiles.

2) Machines with multiple GPU devices. If the application is not designed to be multi-threaded, it would have no way of taking advantage of multiple GPUs.

@umar456, do you agree that for these use cases it's important to write the application as multi-threaded. And if so, shouldn't we make sure that ArrayFire does not prevent, nor create unnecessary bottlenecks for, such usage?

**Comment by pavanky** [comment]
@vakopian 

FYI

1) Should not require multi threading support in individual backends if you are using only one thread per backend. We may need to fix the stuff in `src/api/unified`.

2) ArrayFire is asynchronous (for the most part).You can hand off `function 1` to GPU 1, `function 2` to GPU 2, `function 3` to GPU 3 in a for loop before `function 1` is completed.  Granted this is a bit ugly but what you are requesting for can be mostly achieved using existing functionality.

**Comment by pavanky** [comment]
Having said that, thread safety is still a very important feature to have.

**Comment by vakopian** [comment]
@pavanky I'm not sure if there is a recommendation in your (1). I was just trying to say that @umar456's recommendation of "not relying on threads to improve performance" is not really viable in some important scenarios. The way I understood that recommendation was this: 

_"since the GPU operations are pushed into a single queue anyway, there is no benefit nor need for multiple threads, and so designing the application as if it's a single threaded program is the recommended way to go"_. 

Is this understanding correct? Do you really recommend making the application quasi-single-threaded? If yes, then I still think that following this recommendation would result in a sub-optimal application for the 2 scenarios I described.

**Comment by pavanky** [comment]
@vakopian No I don't mean that at all :) 

I was just letting you know the workarounds for now if this is a blocking feature.

**Comment by WilliamTambellini** [comment]
Good morning,
What is the current status of this one: still early WIP ? halfly done ? mostly done ready for 3.5 ? done ?
Kind

**Comment by pavanky** [comment]
@WilliamTambellini check #1706 for the progress being made.
