### ISSUE TITLE
susan corner dectector

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#911]
[Susan Corner Detector](https://en.wikipedia.org/wiki/Corner_detection#The_SUSAN_corner_detector)

**Comment by 9prady9** [comment]
@pentschev I am thinking of the following API, let me know what you think. I might have missed some parameters, not sure though.

```C
af_err af_susan(af_features* out, const af_array in, const unsigned nuclei_radius, const float gray_diff_thr, const float geometric_thr);
```

```C++
features susan(const array& in, const unsigned nuclei_radius, const float gray_diff_thr, const float geometric_thr);
```

**Comment by pentschev** [comment]
@9prady9 looks good, I would suggest only some name changes (I feel they are too long), plus, you need a feature_ratio (as FAST has) since we don't know in advance the number of features in an image, so we would like to keep this adjustable. Another argument that may be useful is the edge length (which necessarily has to be >= radius-1, if edge is 0, use radius-1), but we may still provide this argument to the API in case the user only wants a smaller part of the image (the inclusion or not of the edge argument is up to you).

```
features susan(const array& in, const unsigned radius, const float diff_thr, const float geom_thr, const unsigned feature_ratio, const unsigned edge);
```

**Comment by 9prady9** [comment]
@pentschev Sure, will add those changes.
