### ISSUE TITLE
Displaying one channel image

### ISSUE THREAD

**Issue by maxineliuqun** [arrayfire/arrayfire#917]
Hi, I am working on medical imaging processing a lot, so all the images are one-channel grayscale images. I would like to display the images, but found out that "image()" in "window" class only supports three-channel images. Is there any way I can get around it or I need to wait until the new feature comes out? Thanks!

**Comment by 9prady9** [comment]
@maxineliuqun grayscale images are supported currently, can you please elaborate on the problem you are facing ?

**Comment by maxineliuqun** [comment]
Thank you for the response. I am trying to send you an image, but it is way too big, so I will send you an email with that image. In order to let other people see it as well, I will explain it in a short way: I have a raw image in a size of 2456*3052, float, intensity ranging from about 200.0f to 255.0f. I read the image in, and tried to display it, but it would not show up. However, when I clicked the window edge, it showed up if I held the mouse click down. I am also wondering if that is because the range is so close, and it is just the display intensity scaling problem or not. I will send you an email with the code and image.

**Comment by 9prady9** [comment]
@maxineliuqun I looked at the code you posted to my email and there are couple of issues with it. To load an image, we have a function [`af::loadImage`](http://www.arrayfire.com/docs/group__imageio__func__load.htm) that helps you load images. Since we use Freeimage to read images from disk, we support all the formats supported by the upstream. When I tried loading the image using `loadImage` function, it threw an error on my end. But based on quick googling, i found that Panasonic Raw format is indeed supported by Freeimage. However, it doesn't seem to work on my end for some reason. Freeimage site seems to be down for maintenance, therefore i couldn't find any more information from their documentation. 

Coming to the point of why the window is not showing anything. I printed the maximum and minimum values of `img` and they turned out to be `0`. Since there is no range to display, the window is showing a black color to us. Are you sure, reading the Raw file  using `ifstream` is correct way to do it ?

You can print extremum of an array using the following code
```
std::cout<< af::max<float>(img) << std::endl;
std::cout<< af::min<float>(img) << std::endl;
```

**Comment by maxineliuqun** [comment]
Thank you for looking into the code and image. I tested it again, the maximum of the "img" is 241.613, and the minimum of the "img" is 199.538. So it looks like the code is alright. Try to change the "newImage.raw" path in the code into wherever you saved the image. I made that mistake before. I tried the "loadImage" API call before, it also threw me an error, and that's why I thought that it might not support it, so I used ifstream.

**Comment by 9prady9** [comment]
@maxineliuqun Also, i forgot to mention something earlier, when you are not using grid mode (i.e. you didn't call Window::grid) function, you don't need to call Window::show, Window::image will do the buffer swap for you. In your code, you were doing the following
```
wnd.image(img/255);
wnd.show(); // this is not needed as above call already does the double buffer swap for you.
```
Let me know if that did change any output on your end. 

Regarding, the file, i just copied the file you provided to the source file location. In any case, I shall check it again.

**Comment by 9prady9** [comment]
@maxineliuqun I checked the path and seems i used wrong path for image file. Now i am able to see a white background, it has speckle noise on it. my code didn't have the `wnd.show` call after `wnd.image`. Is what i see correct ?

**Comment by maxineliuqun** [comment]
Ah, I see. Yeah, I deleted "wnd.show()", and now it all worked! Thank you so much. A quick question, do you know why "loadImage" does not support this type of image? I checked the document, too. It said it could support raw image, as long as the data type is supported. In this case, it is float (actually the  original image is unsigned short, and since it does not support this type, I converted it to float), so I think it is supposed to support it, right?

**Comment by 9prady9** [comment]
No problem. 

Yes, i was under the same impression that it should be loaded without any issues.  The [freeimage website](http://freeimage.sourceforge.net/) is still down, so i can't access their documentation still.

**Comment by maxineliuqun** [comment]
I will check with it when it is up running again. Thank you so much for the help!

**Comment by 9prady9** [comment]
Your welcome.

Closing the issue.
